var ConfigGPack=function(){this.vPoint=this.goldValue=this.xuCost=null},DataPaymentTrans=cc.Class.extend({ctor:function(){this.countryId=this.paymentType=this.paymentSystem=this.telcoChannel="";this.amount=0;this.serial=this.pinCode=this.email="";this.isWebView=!1;this.orderDesc=this.extraData="";this.needOtp=!1}}),DataZingCardTrans=cc.Class.extend({ctor:function(){this.pmcID=this.serial=this.pinCode=this.embedData=this.platform=null}}),GUIStoreBase=BaseGUI.extend({_className:"GUIStoreBase",ctor:function(a){this._super();
this.btnPurchaseCashCard=this.imgTitle=this.imgEditBoxPinCode=this.imgEditBoxSerial=this.imgOperatorChoose=this.btnOperator_3=this.btnOperator_2=this.btnOperator_1=this.btnOperator_0=this.btnChooseOperators=this.ebNumberPhone=this.lbNumberPhone=this.nodeInputPhoneNumber=this.lbChooseOperators=this.nodeSelectDCBOperator=this.ebPinCode=this.ebSerial=this.nodeTelco=this.nodeDCB=this.nodeIAP=this.btnCloseWebView=this.bgWebView=this.nodeWebView=this.nodeChannels=this.tvChannels=this.lvChannels=this.bgBtnRegister=
this.btnRegister=this.htmlMsgRegister=this.imgVipIcon=this.bgRegister=this.lbGold=this.bgShelf=this.imgBg=this.btnClose=null;this.listChannel=[];this.listTelcoButtons=[];this.curDCBPack=this.curSMSPack=this.dataDCBOperators=this.dataSMSOperators=this.dataDCBPacks=this.dataSMSPacks=this.dataIAPPacks=this.dataChannels=null;this._initTelco=this._initDCB=this._initSMS=this._initIAP=!1;this._itemType=a;this._maxVipLevel=3;this._currentVipLevel=null;this.lastLevel=0;this.init()},init:function(){this._super();
this.setDeepSyncChildren(4);this.syncAllChildren(res.node_p_store,this);this.alignCenter();this._resizeGUI();this._leftPartWidth=this.bgShelf.getPositionX()-this.imgBg.getPositionX();this._rightPartWidth=this.bgShelf.getContentSize().width;this._centerOfRightPart=this._rightPartWidth>>1;this._heightPartRight=320;this.btnRegister.setTitleStroke("#944313",1);this.btnPurchaseCashCard.setTitleStroke("#197315",1);this.btnChooseOperators.setTitleStroke("#0f5674",1);this.ebNumberPhone.setPlaceHolderColor(cc.color("#E5E5E5"));
this.htmlMsgRegister.setMode(HtmlTextMode.WRAP_WIDTH,cc.size(480,10));this.htmlMsgRegister.setDefaultFontColor(cc.color("#e4adb9"));this.ebNumberPhone.setRealColor(cc.color("#9f8dad"));this.ebNumberPhone.setPlaceHolderColor(cc.color("#82738D"));this._currentVipLevel=playerModule.getPlayerInfo().vipLevel;this.lastLevel=playerModule.getLevel();this.initStoreLogo();this.initChannels();this.initDCB();this.initTelco();this.loadDefault();this.reloadUI()},_resizeGUI:function(){var a=cc.director.getWinSize().width/
MAX_DESIGN_SIZE.width,b=cc.director.getWinSize().height/MAX_DESIGN_SIZE.height;this._rootNode.setScale(a>b?b:a)},initChannels:function(){this.listChannel.splice(0);PaymentUtils.isLocalDCBSupported(servicesMgr.getCountry(),servicesMgr.getListPaymentMethods())&&this.listChannel.push(ChannelStore.DCB);PaymentUtils.isLocalTelcoSupported(servicesMgr.getCountry(),servicesMgr.getListPaymentMethods())&&this.listChannel.push(ChannelStore.CASH_CARD);this._initDataChannels();this._initUIChannels()},initDCB:function(){if(this.isEnableChannel(ChannelStore.DCB)&&
(this.dataDCBPacks=_.sample(resourceMgr.getConfigDCBPack()))){var a=this;this.dataDCBOperators=PaymentUtils.getAvailableOperators(servicesMgr.getCountry(),servicesMgr.getListPaymentMethods(),!0);this.dataDCBOperators=_.filter(this.dataDCBOperators,function(a){return a==TELCO_CHANNELS.MPT?playerModule.getLevel()>=MIN_LEVEL_TO_OPEN_CODA||paymentModule.isFreeTime():!0});for(var b=0;4>b;b++){var c="";switch(this.dataDCBOperators[b]){case TELCO_CHANNELS.TELENOR:c=res.img_p_telenor;break;case TELCO_CHANNELS.OOREDOO:c=
res.img_p_ooredoo;break;case TELCO_CHANNELS.MPT:c=res.img_p_mpt}""!=c?(this["btnOperator_"+b].setVisible(!0),this["btnOperator_"+b].getChildByName("itemLogo").setTexture(c)):this["btnOperator_"+b].setVisible(!1)}this.btnOperator_0.setPositionX(155);this.btnOperator_2.setPositionX(155);3==this.dataDCBOperators.length?this.btnOperator_2.setPositionX(245):1==this.dataDCBOperators.length&&this.btnOperator_0.setPositionX(245);this.nodeInputPhoneNumber.setPositionY(50);this.lbChooseOperators.ignoreContentAdaptWithSize(!0);
this.lbNumberPhone.ignoreContentAdaptWithSize(!0);this.ebNumberPhone.setInputMode(cc.EDITBOX_INPUT_MODE_NUMERIC);this.ebNumberPhone.setMaxLength(20);this.btnChooseOperators.setTitleStroke("#3B61BF",1);this.dataDCBPacks=_(this.dataDCBPacks).map(function(a,b){a.index=b;return a}).orderBy(["gold"],["asc"]).value();var b=this._rightPartWidth,c=cc.size(500,92),d=this._rightPartWidth<c.width?this._rightPartWidth/c.width:1;this._initDCB||(this.tvDCB=new CustomTableView(this,cc.size(b,this._heightPartRight),
cc.SCROLLVIEW_DIRECTION_VERTICAL),this.tvDCB.setCellClass(this.getClassItemDCB(),this,d).setCellSize(cc.size(c.width*d,c.height*d)).setUpdateDataAtIndex(function(b,c){b.setData(a.dataDCBPacks[c],c)}).setNumberOfCellsCb(function(){return a.dataDCBPacks.length}),this.tvDCB.setTouchEnabled(!0),this.tvDCB.reloadData(),this.nodeDCB.addChild(this.tvDCB));this._initDCB=!0}},initIAP:function(){if(!this._initIAP&&(this.isEnableChannel(ChannelStore.IAP_Android)||this.isEnableChannel(ChannelStore.IAP_IOS))){var a=
this._rightPartWidth,b=cc.size(500,92),c=this._rightPartWidth<b.width?this._rightPartWidth/b.width:1,d=this;this.dataIAPPacks=resourceMgr.getConfigIAPPacks();this.tvIAPShelf=new CustomTableView(this,cc.size(a,this._heightPartRight),cc.SCROLLVIEW_DIRECTION_VERTICAL);this.tvIAPShelf.setCellClass(this.getClassItemIAP(),this,c).setCellSize(cc.size(b.width*c,b.height*c)).setUpdateDataAtIndex(function(a,b){a.setData(d.dataIAPPacks[b],b)}).setNumberOfCellsCb(function(){return d.dataIAPPacks.length});this.tvIAPShelf.reloadData();
this.nodeIAP.addChild(this.tvIAPShelf);this._initIAP=!0}},initPaymentWebView:function(){if(cc.sys.platform!=cc.sys.WIN32&&null==this.wvPayment){var a=cc.size(this.bgWebView.width,this.bgWebView.height-25);this.wvPayment=new ccui.WebView("google.com.vn");this.wvPayment.setVisible(!1);this.wvPayment.setContentSize(a);this.wvPayment.setScalesPageToFit(!0);this.wvPayment.setPosition(this.bgWebView.width>>1,this.bgWebView.height-25>>1);this.nodeWebView.addChild(this.wvPayment,-1);Popups.monitorWebView(this.wvPayment)}this.nodeSelectDCBOperator.setVisible(!1);
this.nodeWebView.setVisible(!0)},initStoreLogo:function(){},initTelco:function(){if(this.isEnableChannel(ChannelStore.CASH_CARD)){this.dataTelco=PaymentUtils.getListTelcoChannel(servicesMgr.getCountry(),servicesMgr.getListPaymentMethods());this.dataShelfTelco=PaymentResourceMgr.getConfig2C2PCardGoldPacks();this.dataShelfTelco=_(this.dataShelfTelco).map(function(a,b){a.index=b;return a}).orderBy(["gold"],["asc"]).value();if(!this._initTelco){var a=this,b=this._rightPartWidth,c=cc.size(500,90);this.tvTelcoShelf=
new CustomTableView(this,cc.size(b,200),cc.SCROLLVIEW_DIRECTION_VERTICAL);this.tvTelcoShelf.setCellClass(this.getClassItemTelco(),this,1).setCellSize(cc.size(1*c.width,1*c.height)).setUpdateDataAtIndex(function(b,c){b.setData(a.dataShelfTelco[c],c)}).setNumberOfCellsCb(function(){return a.dataShelfTelco.length});this.nodeTelco.addChild(this.tvTelcoShelf)}this.tvTelcoShelf.reloadData();this._initTelco=!0}},localize:function(){this._super();this._loadMsgRegister();this.lbChooseOperators.setString(languageMgr.getString("CHOOSE_OPERATOR"));
this.lbNumberPhone.setString(languageMgr.getString("ENTER_PHONE_NUMBER"));this.ebNumberPhone.setPlaceHolder(languageMgr.getString("ENTER_SOMETHING"));this.imgTitle.setTexture(languageMgr.getImgPath("title_shop"))},_loadMsgRegister:function(){var a=playerModule.getPlayerInfo().vipLevel+1,b=resourceMgr.getConfigVip()[a];if(null!=b){this.htmlMsgRegister.setVisible(!0);this.btnRegister.setVisible(!0);this.imgVipIcon.setVisible(!0);var c=languageMgr.getString("NAME_VIP_"+a),b=parseInt(100*b.buyGoldBonusRate);
this.imgVipIcon.setSpriteFrame("icon_vip_@level.png".replace("@level",a));this.htmlMsgRegister.setString(languageMgr.getString("VIP_UPGRADE_MSG").replace("@vipName",c).replace("@percent",b))}else this.htmlMsgRegister.setVisible(!1),this.btnRegister.setVisible(!1),this.imgVipIcon.setVisible(!1),ZLog.debug("config null")},onShowComplete:function(){},onTouchUIEndEvent:function(a){this.setVisibleWebView(!1);var b=this._super(a);if(b)return b;switch(a){case this.btnClose:this.hide();break;case this.btnIAPIOS:cc.sys.isNative?
this.selectChannelStore(ChannelStore.IAP_IOS):Popups.showMessage(languageMgr.getString("COMING_SOON"));break;case this.btnIAPAndroid:cc.sys.isNative?this.selectChannelStore(ChannelStore.IAP_Android):Popups.showMessage(languageMgr.getString("COMING_SOON"));break;case this.btnDCB:this.selectChannelStore(ChannelStore.DCB);break;case this.ebNumberPhone:case this.ebPinCode:case this.ebSerial:sceneMgr.showGUIEditBox(a);break;case this.btnOperator_0:case this.btnOperator_1:case this.btnOperator_2:case this.btnOperator_3:this._chooseOperators(a);
break;case this.btnChooseOperators:this.processPaymentDCB();break;case this.btnPurchaseCashCard:this.processPaymentCashCard();break;case this.btnRegister:sceneMgr.viewSceneById(GV.SCENE_IDS.REGISTER_VIP);this.hide();break;case this.btnCloseWebView:this.selectChannelStore(this.channelStore,this.telcoChannel);break;default:return!1}return!0},tableCellTouched:function(a,b){a==this.tvDCB&&(this.setCurrentPack(b.getData()),this.showSelectDCBOperator())},getClassItemChannels:function(){return ItemStoreChannels},
getClassItemDCB:function(){return ItemStoreDCB},getClassItemIAP:function(){return ItemStoreIAP},getClassItemTelco:function(){return ItemStoreTelco},getItemType:function(){return this._itemType},hide:function(a){this.setVisibleWebView(!1);this._super(a)},isEnableChannel:function(a){for(var b=0;b<this.listChannel.length;++b)if(a==this.listChannel[b])return!0;return!1},loadDefault:function(){this.selectChannelStore(this.dataChannels[0].channels,this.dataChannels[0].telcoName)},loadPaymentURL:function(a){a=
a.replace("https:/","http:/");this.initPaymentWebView();this.wvPayment?(this.wvPayment.setVisible(!0),this.wvPayment.loadURL(a)):ZLog.error("loadPaymentURL fail | "+a+" | webView null")},processPaymentDCB:function(){if(null==this.operatorName)Notifications.show("Please choose Operator!!!");else{var a=PaymentResourceMgr.getConfigPaymentDCBByOperator(servicesMgr.getCountry(),this.operatorName);if(0>a)switch(a){case PS_ERROR.COUNTRY_NOT_FOUND:Popups.showMessage("Can't not find you country");break;case PS_ERROR.OPERATOR_NOT_FOUND:Popups.showMessage("Can't not find config that operator")}else{if(PaymentUtils.isNeedPhoneNumber(a[0])){var b=
this.ebNumberPhone.getRealString().trim();fr.UserData.setString(UserDataKey.PHONE_NUMBER+this.operatorName,b);if(""==b){Notifications.show("Please input your phone number!!!");return}}var a=a[0],c=this.getCurrentPack(),b={paymentItem:PAYMENT_ITEMS.GOLD,operator:this.operatorName,phoneNumber:b,cost:c.cost},a=_.assignWith(b,a,function(a,b){return _.isUndefined(a)?b:a});ZLog.json("purchaseInfo",b);ZLog.json("paymentTypeData",a);paymentModule.getSMSTransaction(b,a)}}},setCurrentPack:function(a){this.currentPack=
a},getCurrentPack:function(){return this.currentPack},processPaymentCashCard:function(){var a=this.ebPinCode.getRealString().trim();this.btnPurchaseCashCard.setTouchEnabled(!1);setTimeout(function(){this.btnPurchaseCashCard.setTouchEnabled(!0)}.bind(this),1E3);var b=this.telcoChannel;if(0<a.length){if(this.imgEditBoxSerial.isVisible()){var c=this.ebSerial.getRealString().trim();if(0==c.length){Popups.showMessage("ENTER_SERIAL");return}}var d=b+"_"+c+"_"+a;if(!PaymentUtils.isValidCardInputFormat(b,
a,c)){OpenTracker.track(TrackingAction.PURCHASE_CARD,"wrong_"+d);Popups.showMessage("NOTIFICATION_CASH_CARD_WRONG_FORMAT_"+b.toUpperCase());return}d="right_"+d;OpenTracker.track(TrackingAction.PURCHASE_CARD,d);moduleMgr.getPaymentModule().purchaseTelco(b,a,c);this.ebPinCode.cleanUpField();this.ebSerial.cleanUpField()}else Popups.showMessage("ENTER_PIN_CODE");c=a=null},reloadConfig:function(){GUI_STORE_DIRTY=!1;ZLog.debug("reload config ...");this.listChannel.splice(0);for(var a=0;a<this.listTelcoButtons.length;++a)this.listTelcoButtons[a].removeFromParent(!0);
this.listTelcoButtons.splice(0);this.initChannels();this.initDCB();this.initTelco();this.reloadUI();this.selectChannelStore();this.localize()},reloadUI:function(){ZLog.json(this.channelStore);if(3<playerModule.getPlayerInfo().vipLevel+1){this.bgRegister.setVisible(!1);var a=cc.p(-160,-200),b=cc.size(this._rightPartWidth,this._heightPartRight+30)}else this.bgRegister.setVisible(!0),a=cc.p(-160,-170),b=cc.size(this._rightPartWidth,this._heightPartRight);(this.isEnableChannel(ChannelStore.IAP_Android)||
this.isEnableChannel(ChannelStore.IAP_IOS))&&this.tvIAPShelf.setViewSize(b);this.isEnableChannel(ChannelStore.DCB)&&this.tvDCB.setViewSize(b);this.isEnableChannel(ChannelStore.CASH_CARD)&&this.tvTelcoShelf.setViewSize(b);this.nodeDCB.setPosition(a);this.nodeIAP.setPosition(a);this.nodeTelco.setPosition(a);this._loadMsgRegister();this.nodeWebView.setVisible(!1);this.nodeInputPhoneNumber.setVisible(!1);this.nodeSelectDCBOperator.setVisible(!1);switch(this.channelStore){case ChannelStore.IAP_Android:case ChannelStore.IAP_IOS:this.nodeIAP.setVisible(!0);
this.tvIAPShelf.reloadData();break;case ChannelStore.DCB:this.nodeDCB.setVisible(!0);this.tvDCB.reloadData();break;case ChannelStore.CASH_CARD:this.showTelcoInput(this.telcoChannel),this.nodeTelco.setVisible(!0),this.tvTelcoShelf.reloadData()}},selectChannelStore:function(a,b,c){if(this.isEnableChannel(a)){this.channelStore=a||this.dataChannels[0].channels;this.telcoChannel=b||this.dataChannels[0].telcoName;for(var d in this.dataChannels)this.dataChannels[d].isHighLight=!(this.dataChannels[d].channels!=
a||this.dataChannels[d].telcoChannel!=b);this.tvChannels.reloadData();this.nodeWebView.setVisible(!1);Popups.hideWebView();this.nodeIAP.setVisible(!1);this.nodeTelco.setVisible(!1);this.nodeDCB.setVisible(!1);this.nodeSelectDCBOperator.setVisible(!1);this.nodeWebView.setVisible(!1);switch(a){case ChannelStore.IAP_Android:case ChannelStore.IAP_IOS:this.nodeIAP.setVisible(!0);break;case ChannelStore.DCB:this.nodeDCB.setVisible(!0);break;case ChannelStore.CASH_CARD:this.showTelcoInput(b),this.nodeTelco.setVisible(!0)}}},
setCurrentDCBPack:function(a){this.curDCBPack=a},setCurrentSMSPack:function(a){this.curSMSPack=a},setSelectedOperator:function(a){this.selectedOperator=a},setVisiblePhoneNumberDCB:function(a,b){if(a&&b){this.nodeInputPhoneNumber.isVisible()||(this.nodeInputPhoneNumber.runAction(cc.sequence(cc.show(),cc.fadeIn(.2))),this.btnChooseOperators.stopAllActions(),this.btnChooseOperators.runAction(cc.moveTo(.3,cc.p(350,50))));var c=fr.UserData.getString(UserDataKey.PHONE_NUMBER+b,"");this.ebNumberPhone.setRealString(c)}else this.nodeInputPhoneNumber.isVisible()&&
(this.nodeInputPhoneNumber.runAction(cc.sequence(cc.fadeOut(.2),cc.hide())),this.btnChooseOperators.stopAllActions(),this.btnChooseOperators.runAction(cc.moveTo(.3,cc.p(245,50))))},setVisibleWebView:function(a){this.wvPayment&&this.wvPayment.setVisible(a)},show:function(a,b){var c=GUI_STORE_DIRTY||3>this.dataDCBOperators.length&&paymentModule.isFreeTime()||1<this.dataDCBOperators.length&&!paymentModule.isFreeTime();c||playerModule.getLevel()==this.lastLevel||(this.lastLevel=playerModule.getLevel(),
c=this.lastLevel>=MIN_LEVEL_TO_OPEN_CODA);c&&this.reloadConfig();ZAccTracker.track(TrackingAction.OPEN_PAYMENT_GUI,this.dataDCBOperators.length);Audio.playEffect(res.s_open_shop);this.updateMyInfo();this.reloadUI();this.selectChannelStore();this._super(a,b)},showSelectDCBOperator:function(a){this.selectedOperator=null;this.nodeIAP.setVisible(!1);this.nodeTelco.setVisible(!1);this.nodeDCB.setVisible(!1);this.nodeSelectDCBOperator.setVisible(!0);this._chooseOperators(a)},showTelcoInput:function(a){this.ebSerial.setInputMode(cc.EDITBOX_INPUT_MODE_NUMERIC);
this.telcoChannel=a;ZLog.debug("Show telco name"+a);this.dataShelfTelco=PaymentResourceMgr.getConfig2C2PCardGoldPacks();this.dataShelfTelco=_(this.dataShelfTelco).filter(function(b){return 1==b.isAvailable[a.toUpperCase()]}).map(function(a,c){a.index=c;return a}).orderBy(["gold"],["asc"]).value();this.tvTelcoShelf.reloadData();switch(a){case TELCO_CHANNELS.AIS:case TELCO_CHANNELS.TRUE:case TELCO_CHANNELS.TELKOMSEL:case TELCO_CHANNELS.EASY_POINTS:this.imgEditBoxSerial.setVisible(!1);this.ebPinCode.setPlaceHolder(languageMgr.getString("ENTER_PIN_CODE_"+
a.toUpperCase()));this.ebPinCode.setInputMode(cc.EDITBOX_INPUT_MODE_NUMERIC);break;case TELCO_CHANNELS.VINA_PHONE:this.ebSerial.setInputMode(cc.EDITBOX_INPUT_MODE_ANY);case TELCO_CHANNELS.ZING:case TELCO_CHANNELS.VIETTEL:case TELCO_CHANNELS.MOBI_PHONE:case TELCO_CHANNELS.MOL_POINTS:case TELCO_CHANNELS.DTAC_HAPPY:this.ebSerial.setPlaceHolder(languageMgr.getString("ENTER_SERIAL_"+a.toUpperCase()));this.ebPinCode.setPlaceHolder(languageMgr.getString("ENTER_PIN_CODE_"+a.toUpperCase()));this.imgEditBoxSerial.setVisible(!0);
break;default:this.imgEditBoxSerial.setVisible(!1),this.ebPinCode.setPlaceHolder(languageMgr.getString("ENTER_PIN_CODE"))}this.imgEditBoxSerial.isVisible()?(this.imgEditBoxPinCode.x=195,this.imgEditBoxPinCode.y=244,this.btnPurchaseCashCard.loadTextures("btn_p_purcharse_2.png","btn_p_purcharse_2.png","btn_p_purcharse_2.png",ccui.Widget.PLIST_TEXTURE)):(this.imgEditBoxPinCode.x=195,this.imgEditBoxPinCode.y=286,this.btnPurchaseCashCard.loadTextures("btn_p_purcharse_1.png","btn_p_purcharse_1.png","btn_p_purcharse_1.png",
ccui.Widget.PLIST_TEXTURE),this.tvTelcoShelf.setViewSize(cc.size(this._rightPartWidth,255)),this.tvTelcoShelf.reloadData())},updateGoldValueInDCB:function(){this.isEnableChannel(ChannelStore.DCB)&&this.tvDCB&&this.tvDCB.reloadData()},updateGoldValueInIAP:function(){(this.isEnableChannel(ChannelStore.IAP_Android)||this.isEnableChannel(ChannelStore.IAP_IOS))&&this.tvIAPShelf&&this.tvIAPShelf.reloadData()},updateGoldValueInSMS:function(){this.isEnableChannel(ChannelStore.SMS)&&this.tvSMS&&this.tvSMS.reloadData()},
updateGoldValueInTelco:function(){this.isEnableChannel(ChannelStore.CASH_CARD)&&this.tvTelcoShelf&&this.tvTelcoShelf.reloadData()},updateMyInfo:function(a){a=void 0===a?playerModule.getMyInfo():a;null!=a&&this.lbGold.setString(Utility.formatMoney(a.gold,""))},updateStoreGold:function(){this.updateGoldValueInDCB()},_chooseOperators:function(a){if(null==a)this.operatorName=null,this.imgOperatorChoose.setVisible(!1),this.btnChooseOperators.setVisible(!1),this.setVisiblePhoneNumberDCB(!1);else{this.operatorName=
this.dataDCBOperators[a.getName().split("_")[1]];var b=PaymentResourceMgr.getConfigPaymentDCBByOperator(servicesMgr.getCountry(),this.operatorName);if(0>b)switch(b){case PS_ERROR.COUNTRY_NOT_FOUND:Popups.showMessage("Can't not find you country");break;case PS_ERROR.OPERATOR_NOT_FOUND:Popups.showMessage("Can't not find config that operator")}else b instanceof Array&&this.setVisiblePhoneNumberDCB(PaymentUtils.isNeedPhoneNumber(b[0]),this.operatorName),this.imgOperatorChoose.setPosition(a.getPositionX()+
1.39,a.getPositionY()+4),this.imgOperatorChoose.setVisible(!0);this.btnChooseOperators.setVisible(!0)}},_initDataChannels:function(){this.dataChannels=[];for(var a in this.listChannel){var b={channels:this.listChannel[a],isHighLight:!1};switch(this.listChannel[a]){case ChannelStore.IAP_IOS:case ChannelStore.IAP_Android:case ChannelStore.DCB:this.dataChannels.push(b);break;case ChannelStore.CASH_CARD:var c=PaymentUtils.getListTelcoChannel(servicesMgr.getCountry(),servicesMgr.getListPaymentMethods()),
d;for(d in c)b=_.clone(b),b.telcoChannel=c[d],this.dataChannels.push(b);break;default:ZLog.error("Can't find channels init data render")}}},_initUIChannels:function(){var a=this,b=cc.size(168,67);this.initChannels.init||(this.tvChannels=new CustomTableView(this,cc.size(168,300),cc.SCROLLVIEW_DIRECTION_VERTICAL),this.tvChannels.setCellClass(this.getClassItemChannels(),this,1).setCellSize(cc.size(1*b.width,1*b.height)).setUpdateDataAtIndex(function(b,d){b.setData(a.dataChannels[d],d)}).setNumberOfCellsCb(function(){return a.dataChannels.length}),
this.nodeChannels.addChild(this.tvChannels),this.initChannels.init=!0);this.nodeDCB.setVisible(!1);this.nodeIAP.setVisible(!1);this.nodeTelco.setVisible(!1);this.nodeSelectDCBOperator.setPosition(this.nodeTelco.getPosition())}}),GUIStoreGold=GUIStoreBase.extend({_className:"GUIStoreGold",ctor:function(){this._super(PAYMENT_ITEMS.GOLD)},init:function(){this._super();this.initVip()},initVip:function(){},onTouchUIEndEvent:function(a){if(a=this._super(a))return a},localize:function(){this._super()}}),
GUIVerifyOtp=BaseGUI.extend({_className:"GUIVerifyOtp",ctor:function(){this._super();this.data=this.ebOTPNumber=this.btnVerify=this.imgBgInput=this.lbMsg=this.lbTitle=this.btnClose=null;this.init()},init:function(){this._super();this.setDeepSyncChildren(2);this.syncAllChildren(res.node_p_verify_otp,this);this.alignCenter();this.lbTitle.ignoreContentAdaptWithSize(!0);this.ebOTPNumber.setMaxLength(20);this.ebOTPNumber.setRealColor(cc.color("#9f8dad"));this.ebOTPNumber.setPlaceHolderColor(cc.color("#E5E5E5"));
this.ebOTPNumber.setInputMode(cc.EDITBOX_INPUT_MODE_NUMERIC);this.btnVerify.setTitleStroke("#bb4d16",1)},onTouchUIEndEvent:function(a){switch(a){case this.ebOTPNumber:sceneMgr.showGUIEditBox(a);break;case this.btnClose:this.hide();break;case this.btnVerify:a=this.ebOTPNumber.getRealString(),0==a.length?Notifications.show("ERROR_OTP_EMPTY"):paymentModule.sendVerifyOtpSea(this.data.paymenttype,this.data.transid,this.data.partnertransid,a)}},hide:function(a){fr.UserData.setString(UserDataKey.TRANS_OTP_DATA,
'{"empty": 1}');this._super(a)},localize:function(){this._super();this.lbTitle.setZString("VERIFY_OTP",!0);this.lbMsg.setString(languageMgr.getString("TEXT_DETAIL_OTP"));this.btnVerify.setTitleText(languageMgr.getString("VERIFY").toUpperCase())},setData:function(a){this.data=a},show:function(a,b){fr.UserData.setString(UserDataKey.TRANS_OTP_DATA,JSON.stringify(this.data));this.ebOTPNumber.setRealString("");this._super(a,b)}}),ItemStoreChannels=BaseTableCell.extend({ctor:function(a,b){this.logo=this.btn=
null;this._super(res.node_p_item_channels);this._cellScale=b;this.setDeepSyncChildren(2);this.syncAllChildren();this.init()},init:function(){this._rootNode.setScale(this._cellScale)},onTouchUIEndEvent:function(a){paymentModule.getGUIStoreGold().selectChannelStore(this._data.channels,this._data.telcoChannel,this._index)},getData:function(){return this._data},setData:function(a,b){this._data=a;this._index=b;this.loadBackGround();this.loadLogo()},loadLogo:function(){var a="img_p_gplay.png";if(this._data.channels==
ChannelStore.CASH_CARD){switch(this._data.telcoChannel){case TELCO_CHANNELS.TELENOR:a=res.img_p_telenor;break;case TELCO_CHANNELS.OOREDOO:a=res.img_p_ooredoo;break;case TELCO_CHANNELS.EASY_POINTS:a=res.img_p_easy_points}this.logo.setTexture(a)}else{switch(this._data.channels){case ChannelStore.IAP_Android:a="img_p_gplay.png";break;case ChannelStore.IAP_IOS:a="img_p_app_store.png";break;case ChannelStore.DCB:a="img_p_sms.png"}this.logo.setSpriteFrame(a)}},loadBackGround:function(){var a="bg_p_channels.png";
this._data.isHighLight&&(a="bg_p_channels_choose.png");this.btn.loadTextures(a,a,a,ccui.Widget.PLIST_TEXTURE)}}),ItemStoreDCB=BaseTableCell.extend({ctor:function(a,b){this.imgStrike=this.itemVPoint=this.lbVipPoint=this.htmlMsg=this.lbTotalGold=this.lbOldGold=this.lbMoney=this.lbCurrency=this.btnPurchase=this.bg=null;this._super(res.node_p_item_shelf_dcb);this._cellScale=b;this.animItem=null;this.setDeepSyncChildren(3);this.syncAllChildren();this.init()},init:function(){this._rootNode.setScale(this._cellScale);
this.lbTotalGold.ignoreContentAdaptWithSize(!0);this.lbVipPoint.ignoreContentAdaptWithSize(!0);this.lbOldGold.ignoreContentAdaptWithSize(!0);this._initAnimItemShop()},_initAnimItemShop:function(){this.animItem=new DBAnimation(res.anim_item_shop);this.animItem.getArmature().setPosition(GV.VISIBALE_SIZE.width>>1,GV.VISIBALE_SIZE.height>>1);this.animItem.getArmature().setPosition(-192,0);this._rootNode.addChild(this.animItem.getArmature())},onTouchUIEndEvent:function(a){ZLog.debug("showSelectDCBOperator");
moduleMgr.getPaymentModule().getGUIStoreGold().setCurrentPack(this._data);moduleMgr.getPaymentModule().getGUIStoreGold().showSelectDCBOperator()},getData:function(){return this._data},setData:function(a,b){this._data=a;this._index=b;var c=paymentModule.isBonus1StPay(this._data.packId),d=playerModule.getVipLevel();if(c)this.lbOldGold.setString(Utility.formatMoneyFull(this._data.gold,"")),this.lbTotalGold.setString(Utility.formatMoneyFull(this._data.gold*(1+this._data.bonus1StPay),"")),this.imgStrike.width=
this.lbOldGold.getContentSize().width,this.htmlMsg.setString(languageMgr.getString("BONUS_FIRST_TIME").replace("@percent",Math.zFloor(100*this._data.bonus1StPay)).replace("@style",res.UTM_AVO_P13_BOLD));else if(0<d){var e=resourceMgr.getConfigVip()[d];this.lbOldGold.setString(Utility.formatMoneyFull(this._data.gold,""));this.lbTotalGold.setString(Utility.formatMoneyFull(this._data.gold*(1+e.buyGoldBonusRate),""));this.imgStrike.width=this.lbOldGold.getContentSize().width;this.htmlMsg.setString(languageMgr.getString("BONUS_VIP").replace("@percent",
Math.zFloor(100*e.buyGoldBonusRate)).replace("@style",res.UTM_AVO_P13_BOLD))}else this.lbTotalGold.setString(Utility.formatMoneyFull(this._data.gold,""));c=c||0<d;this.lbOldGold.setVisible(c);this.imgStrike.setVisible(c);this.htmlMsg.setVisible(c);this.lbCurrency.setString(PaymentUtils.getCurrency());this.lbMoney.setString(Utility.formatMoneyFull(this._data.cost,""));this.lbVipPoint.setString("+"+this._data.vPoint);c=6;6>b&&(c=b);this.animItem.playForever(""+(6-c))}}),ItemStoreIAP=BaseTableCell.extend({ctor:function(a,
b){this.imgStrike=this.itemGold=this.itemVPoint=this.lbVipPoint=this.htmlMsg=this.lbTotalGold=this.lbOldGold=this.lbMoney=this.lbCurrency=this.btnPurchase=this.bg=null;this._super(res.node_p_item_shelf_iap);this._cellScale=b;this.setDeepSyncChildren(2);this.syncAllChildren();this.init()},init:function(){this._rootNode.setScale(this._cellScale);this.lbTotalGold.ignoreContentAdaptWithSize(!0);this.lbVipPoint.ignoreContentAdaptWithSize(!0);this.lbOldGold.ignoreContentAdaptWithSize(!0)},onTouchUIEndEvent:function(a){ZLog.debug("purchaseIAP");
moduleMgr.getPaymentModule().purchaseIAP(this._data.productId,PAYMENT_ITEMS.GOLD)},getData:function(){return this._data},setData:function(a,b){this._index=b;this._data=a;this.lbCurrency.setString(PaymentUtils.getCurrency());this.lbMoney.setString(Utility.formatMoneyFull(this._data.usdCost,""));this.lbOldGold.setString(Utility.formatMoneyFull(.8*this._data.gold,""));this.lbTotalGold.setString(Utility.formatMoneyFull(this._data.gold,""));this.lbVipPoint.setString("+"+this._data.vPoint);this.lbVipPoint.setPositionX(this.lbTotalGold.getPositionX()+
this.lbTotalGold.getContentSize().width+5);this.itemVPoint.setPositionX(this.lbVipPoint.getPositionX()+this.lbVipPoint.getContentSize().width+5);this.htmlMsg.setString(this._data.productId);this.imgStrike.width=this.lbOldGold.getContentSize().width;var c=6;6>b&&(c=b);this.itemGold.setSpriteFrame("icon_p_gold_"+c+".png")}}),ItemStoreTelco=BaseTableCell.extend({ctor:function(a,b){this.imgStrike=this.itemVPoint=this.lbVipPoint=this.htmlMsg=this.lbTotalGold=this.lbOldGold=this.lbMoney=this.lbCurrency=
this.bg=null;this._super(res.node_p_item_shelf_telco);this._cellScale=b;this.setDeepSyncChildren(2);this.syncAllChildren();this.init()},init:function(){this._rootNode.setScale(this._cellScale);this.lbTotalGold.ignoreContentAdaptWithSize(!0);this.lbVipPoint.ignoreContentAdaptWithSize(!0);this.lbOldGold.ignoreContentAdaptWithSize(!0);this.imgStrike.setVisible(!1);this.lbOldGold.setVisible(!1);this.htmlMsg.setVisible(!1);this._initAnimItemShop()},_initAnimItemShop:function(){this.animItem=new DBAnimation(res.anim_item_shop);
this.animItem.getArmature().setPosition(GV.VISIBALE_SIZE.width>>1,GV.VISIBALE_SIZE.height>>1);this.animItem.getArmature().setPosition(-192,0);this._rootNode.addChild(this.animItem.getArmature())},getData:function(){return this._data},setData:function(a,b){this._data=a;this.lbCurrency.setString(PaymentUtils.getCurrency());this.lbMoney.setString(Utility.formatMoneyFull(this._data.cost,""));this.lbVipPoint.setString("+"+this._data.vPoint);var c=playerModule.getVipLevel();if(0<c){var d=resourceMgr.getConfigVip()[c];
this.lbOldGold.setString(Utility.formatMoneyFull(this._data.gold,""));this.lbTotalGold.setString(Utility.formatMoneyFull(this._data.gold*(1+d.buyGoldBonusRate),""));this.imgStrike.width=this.lbOldGold.getContentSize().width;this.htmlMsg.setString(languageMgr.getString("BONUS_VIP").replace("@percent",Math.zFloor(100*d.buyGoldBonusRate)).replace("@style",res.UTM_AVO_P13_BOLD))}else this.lbTotalGold.setString(Utility.formatMoneyFull(this._data.gold,""));c=0<c;this.lbOldGold.setVisible(c);this.imgStrike.setVisible(c);
this.htmlMsg.setVisible(c);c=6;6>b&&(c=b);this.animItem.playForever(""+(6-c))}});CmdReceiveIAPAndroid=BaseInPacket.extend({ctor:function(){this._super();this.signature=this.purchaseData=null},readData:function(){var a=this.getString();try{this.purchaseData=JSON.parse(a)}catch(b){this.purchaseData={},ZLog.debug("JSON parse error: "+a)}this.signature=this.getString()}});
CmdReceiveIAPIOs=BaseInPacket.extend({ctor:function(){this._super();this.transList=[]},readData:function(){for(var a=this.getShort(),b=0;b<a;++b)this.transList.push({productId:this.getString(),quantity:this.getInt()})}});CmdReceivePaymentTrans=BaseInPacket.extend({readData:function(){this.retCode=this.getInt();this.transId=this.getString();this.url=this.getString();this.partnerTransId=this.getString();this.shortCode=this.getString();this.message=this.getString();this.instruction=this.getString()}});
CmdReceiveZMPSubmitCard=BaseInPacket.extend({readData:function(){this.retCode=this.getInt();this.transID=this.getLong()}});
CmdReceiveZMPRegSMS=BaseInPacket.extend({ctor:function(){this._super();this.smsServicePhones=this.returnMessage=this.transID=this.retCode=null},readData:function(){this.retCode=this.getInt();this.transID=this.getLong();this.returnMessage=this.getString();if(this.retCode==ZING_CARD_CODE.SUCCESS)try{var a=this.getString();this.smsServicePhones=JSON.parse(a)}catch(b){ZLog.error("CmdReceiveZMPRegSMS: error parse smsServicePhones: "+a)}}});
CmdReceiveZMPGetStatus=BaseInPacket.extend({ctor:function(){this._super();this.ppValue=this.isProcessing=this.returnMessage=this.transID=this.retCode=null},readData:function(){this.retCode=this.getInt();this.transID=this.getLong();this.returnMessage=this.getString();this.isProcessing=this.getBool();this.ppValue=this.getLong()}});
CmdReceivePaymentUpdate=BaseInPacket.extend({ctor:function(){this._super();this.other=this.amount=this.paymentItem=this.paymentChannel=this.providerID=null},readData:function(){this.providerID=this.getInt();this.paymentChannel=this.getInt();this.paymentItem=this.getInt();this.amount=this.getLong();this.other=this.getString()}});CmdReceiveSeaVerifyOtp=BaseInPacket.extend({ctor:function(){this._super();this.retCode=null},readData:function(){this.retCode=this.getInt()}});
CmdReceiveFirstPayUpdate=BaseInPacket.extend({ctor:function(){this._super();this.listBonus1StPay=[]},readData:function(){for(var a=this.getShort(),b=0;b<a;b++)this.listBonus1StPay.push(this.getString())}});CmdSendIAPAndroid=BaseOutPacket.extend({ctor:function(a,b){this._super();this.data=a;this.paymentItem=b;this.initData(10);this.setCmdId(CMD.PAYMENT_IN_APP_PURCHASE_ANDROID)},putData:function(){this.putString(JSON.stringify(this.data.purchaseData));this.putString(this.data.signature);this.putInt(this.paymentItem)}});
CmdSendIAPIOs=BaseOutPacket.extend({ctor:function(a,b){this._super();this.receipt=a;this.paymentItem=b;this.initData(2);this.setCmdId(CMD.PAYMENT_IN_APP_PURCHASE_IOS)},putData:function(){this.putString(this.receipt);this.putInt(this.paymentItem)}});
CmdSendPaymentTrans=BaseOutPacket.extend({ctor:function(a){this._super();this.data=a;this.initData(2);this.setCmdId(CMD.PAYMENT_CREATE_TRANS)},putData:function(){this.putInt(this.data.paymentType);this.putString(this.data.countryId);this.putLong(this.data.amount);this.putString(this.data.email);this.putString(this.data.pinCode);this.putString(this.data.serial);this.putString(this.data.extraData);this.putString(this.data.orderDesc)}});
CmdSendZMPSubmitCard=BaseOutPacket.extend({ctor:function(a){this._super();this.data=a;this.initData(2);this.setCmdId(CMD.PAYMENT_ZMP_SUBMIT_CARD)},putData:function(){this.putString(this.data.platform);this.putString(this.data.embedData);this.putString(this.data.serial);this.putString(this.data.pinCode);this.putInt(this.data.pmcID)}});
CmdSendZMPRegSMS=BaseOutPacket.extend({ctor:function(a){this._super();this.data=a;this.initData(2);this.setCmdId(CMD.PAYMENT_ZMP_REG_SMS)},putData:function(){this.putString(this.data.platform);this.putString(this.data.embedData);this.putLong(this.data.amount);this.putString(this.data.netWorkOperation)}});CmdSendZMPGetStatus=BaseOutPacket.extend({ctor:function(a){this._super();this.transID=a;this.initData(2);this.setCmdId(CMD.PAYMENT_ZMP_GET_STATUS)},putData:function(){this.putLong(this.transID)}});
CmdSendVerifyOtpSea=BaseOutPacket.extend({ctor:function(a){this._super();this.data=a;this.initData(2);this.setCmdId(CMD.PAYMENT_SEA_VERIFY_OTP)},putData:function(){this.putString(this.data.transId);this.putString(this.data.partnerTransId);this.putInt(this.data.paymentType);this.putString(this.data.otp)}});CmdSendFirstPayUpdate=BaseOutPacket.extend({ctor:function(){this._super();this.initData(2);this.setCmdId(CMD.PAYMENT_FIRST_PAY_UPDATE)}});
fr.bluepay={privateProductId:"0305",liveProductId:"0293",createSMS:function(a,b,c){var d;d="2@productId@transId".replace("@productId",GV.MODE==BUILD_MODE.LIVE?this.liveProductId:this.privateProductId);d=d.replace("@transId",c);return{phoneNo:this.getPhoneNo(a,b),msg:d}},getPhoneNo:function(a,b){return resourceMgr.getConfigBluePayPhoneNoSMSByAmount(a,b)}};
fr.coda={productId:"",createSMS:function(a,b,c){a=servicesMgr.getCountry();var d;return a==COUNTRY.INDO&&(b==TELCO_CHANNELS.TELKOMSEL||b==TELCO_CHANNELS.XL)||a==COUNTRY.MYANMAR&&b==TELCO_CHANNELS.OOREDOO?(b=c.split('"'),0<b.length&&(d=b[1]),b=c.split("."),c=b[0].split(" "),c=c[c.length-1],{phoneNo:c,msg:d}):c}};fr.fortumo={productId:"50001",createSMS:function(a,b){return{phoneNo:a,msg:b}}};fr.ipayy={productId:"50001",createSMS:function(a,b){return{phoneNo:a,msg:b}}};
fr.mol={productId:"50001",createSMS:function(a,b,c){var d=servicesMgr.getCountry(),d=d==COUNTRY.INDO?"@code 4203 @transId".replace("@code",this.getCode(a)):d==COUNTRY.MALAYSIA?"@code 4210 @transId".replace("@code",this.getCode(a)):"4142 @transId @productId".replace("@productId",this.productId),d=d.replace("@transId",c);return{phoneNo:this.getPhoneNo(a,b),msg:d}},getPhoneNo:function(a,b){return resourceMgr.getConfigMOLPhoneNoSMSByAmount(a,b)},getCode:function(a){return resourceMgr.getConfigMOLCodeSMSByAmount(a)}};
var DAY_OLD_CAN_SHOW_FIRST_PAY=.25,DELAY_SHOW_FIRST_PAY=28800,GUI_STORE_DIRTY=!1,MIN_LEVEL_TO_OPEN_CODA=5,FREE_TIME_TO_ENABLE_TELCO=1;ChannelStore={IAP_IOS:0,IAP_Android:1,CASH_CARD:2,SMS:3,DCB:4,SHOP:5};var IAP_PURCHASE_DELAY=1E3;PS_ERROR={COUNTRY_NOT_FOUND:-1,OPERATOR_NOT_FOUND:-2,PAYMENT_TYPE_NOT_FOUND:-3,PARAM_INVALID:-4};PAYMENT_ITEMS={GOLD:1,XU:2,SAFE_BOX:3};PAYMENT_ITEMS_NAME={GOLD:"GOLD",XU:"XU",SAFE_BOX:"SAFE_BOX",VPOINT:"VPOINT",EXP:"EXP",UP_VIP:"UP_VIP"};
PAYMENT_CHANNELS={SMS:0,CARD:1,ZING_CARD:2,PRE_PAID_CARD:3,E_WALLET:4,IAP:5,UNKNOWN:6};PAYMENT_SYSTEM={EMPTY:"empty",ZALO:"zalo",BLUE_PAY:"bluepay",MOL:"mol",IAP:"iap",ZMPAY:"zmp",CODA:"coda",_2C2P:"2c2p",IPAYY:"ipayy"};
TELCO_CHANNELS={ZING:"zing",VIETTEL:"viettel",VINA_PHONE:"vina",MOBI_PHONE:"mobi",DTAC_HAPPY:"dtac",TRUE:"true",AIS:"ais",MOL_POINTS:"mol",TELKOMSEL:"telkomsel",INDOSAT:"indosat",XL:"xl",HUTCHISON:"hutchison",MAXIS:"maxis",DIGI:"digi",CELCOM:"celcom",U_MOBILE:"umobile",TELENOR:"telenor",OOREDOO:"ooredoo",EASY_POINTS:"easy_points",MPT:"mpt",IDEA:"idea",AIRCEL:"aircel",RELIANCE:"reliance",VODAFONE:"vodafone",AIRTEL:"airtel",BSNL:"bsnl",TATA:"tata"};
CURRENCY={VND:"VND",IDR:"IDR",THB:"THB",MYR:"MYR",MMK:"MMK",INR:"INR",USD:"USD"};var PAY_ZING_URL="https://pay.play.zing.vn/login/poker",Z_ORDER=Z_ORDER||{};Z_ORDER.PAYMENT_GUI=100;
CARD_REG={viettel:{SERIAL:/^([0-9]{11})$/,PIN_CODE:/^([0-9]{13})$/},vina:{SERIAL:/^([A-Za-z0-9]{14})$/,PIN_CODE:/^([0-9]{14})$/},mobi:{SERIAL:/^([0-9]{15})$/,PIN_CODE:/^([0-9]{12})$/},dtac:{SERIAL:/^([0-9]{10})$/,PIN_CODE:/^([0-9]{6})$/},"true":{SERIAL:/^([0-9]{14})$/,PIN_CODE:/^([0-9]{14})$/},ais:{SERIAL:/^([0-9]{16})$/,PIN_CODE:/^([0-9]{16})$/},mol:{SERIAL:/^([0-9]{10})$/,PIN_CODE:/^([0-9]{14})$/},easy_points:{SERIAL:/^([0-9]{18})$/,PIN_CODE:/^([0-9]{18})$/}};
var PaymentModule=BaseModule.extend({_className:"PaymentModule",ctor:function(a){this._super(a);this._curCashCardTrans=this._curSMSTrans=null;this._lastPackSMS={pack:null,type:PAYMENT_ITEMS.GOLD};this._lastPackIAP={pack:null,type:PAYMENT_ITEMS.GOLD};this._guiStoreItem=null;this.setListenerValue(8E3,8800)},processPackages:function(a){if(null==this._curPackage)cc.warn("%s NOT FOUND curPackage with cmd (%d)",this.getClassName(),a);else{var b=this._curPackage.getError();playerModule.getVipLevel();playerModule.getGold();
switch(a){case CMD.PAYMENT_IN_APP_PURCHASE_ANDROID:b==ERROR_CODE.SUCCESS||b==ERROR_CODE.PAYMENT_TRANSACTION_DUPLICATED||b==ERROR_CODE.PAYMENT_TRANSACTION_SANDBOX_TO_PRODUCTION?fr.iap.finishTransactions(this._curPackage.purchaseData,this._curPackage.signature):Popups.showError(b);break;case CMD.PAYMENT_IN_APP_PURCHASE_IOS:sceneMgr.hideGUIWaiting();b==ERROR_CODE.SUCCESS?fr.iap.finishTransactions(this._curPackage.transList):(this._curPackage.transList&&0<this._curPackage.transList.length&&fr.iap.finishTransactions(this._curPackage.transList,
!1),Popups.showError(b));break;case CMD.PAYMENT_CREATE_TRANS:a=this._curPackage.retCode;a==TRANS_ERROR_CODE.SUCCESS?(sceneMgr.hideGUIWaiting(),null!=this._curSMSTrans?(this._curSMSTrans.isWebView?lobbyModule.getGUIWebView().loadURLWebView(this._curPackage.url):this._curSMSTrans.needOtp?this.showGUIVerifyOtp(this._curSMSTrans.paymentType,this._curPackage.transId,this._curPackage.partnerTransId):this._curPackage.transId&&0<this._curPackage.transId.length?this.sendSMS(this._curPackage):Popups.showMessage("SMS trans ID not found"),
this._curSMSTrans=null):null!=this._curCashCardTrans&&(this._guiStoreGold&&this._guiStoreGold.isVisible()?lobbyModule.getGUIWebView().loadURLWebView(this._curPackage.url):this._guiStoreItem&&this._guiStoreItem.isVisible()&&this._guiStoreItem.loadPaymentURL(this._curPackage.url),this._curCashCardTrans=null)):this.showGetTransError(a);break;case CMD.PAYMENT_ZMP_SUBMIT_CARD:a=this._curPackage.retCode;a!=ZING_CARD_CODE.SUCCESS&&this.sendZMPGetStatus(this._curPackage.transID);break;case CMD.PAYMENT_ZMP_REG_SMS:a=
this._curPackage.retCode;a==ZING_CARD_CODE.SUCCESS?(sceneMgr.hideGUIWaiting(),fr.platformWrapper.sendSMS(this._curPackage.smsServicePhones.servicePhone,this._curPackage.smsServicePhones.smsSyntax)):this.showZMPError(a,this._curPackage.returnMessage);break;case CMD.PAYMENT_ZMP_GET_STATUS:a=this._curPackage.retCode;a!=ZING_CARD_CODE.SUCCESS?this.showZMPError(a,this._curPackage.returnMessage):sceneMgr.hideGUIWaiting();break;case CMD.PAYMENT_UPDATE:b==ERROR_CODE.SUCCESS?this._curPackage.paymentItem==
PAYMENT_ITEMS.GOLD&&(this._curPackage.paymentChannel==PAYMENT_CHANNELS.SMS?(SMS_CALLBACK=!1,(a=resourceMgr.getConfigSMSByKey(this._curPackage.other))?(playerModule.addVipPoint(a.vPoint),a=fr.UserData.getString(UserDataKey.MY_OPERATOR_TMP,""),0<a.length&&(fr.UserData.setString(UserDataKey.MY_OPERATOR,a),fr.UserData.setString(UserDataKey.MY_OPERATOR_TMP,""),OpenTracker.track(TrackingAction.OPERATOR_SUCCESS,a)),this.addBonus1StPay(this._curPackage.other)):Popups.showMessage("Doesn't have config"),this._guiStoreGold&&
this._guiStoreGold.isVisible()&&this._guiStoreGold.setVisibleWebView(!1)):this.isPaymentByCard(this._curPackage.paymentChannel)&&(a=resourceMgr.getConfigCardByKey(this._curPackage.other))&&playerModule.addVipPoint(a.vPoint),a=this._curPackage.amount,playerModule.addGold(a),playerModule.showGUIReceiveGold(a),this.getGUIStoreGold().isVisible()&&(this.getGUIStoreGold().reloadUI(),this.getGUIStoreGold().updateMyInfo()),sceneMgr.isScene(GV.SCENE_IDS.REGISTER_VIP)&&sceneMgr.getCurrentScene().updateInfoPlayer&&
sceneMgr.getCurrentScene().updateInfoPlayer()):Popups.showError(b);break;case CMD.PAYMENT_SEA_VERIFY_OTP:a=this._curPackage.retCode;a==TRANS_ERROR_CODE.SUCCESS?this.hideGUIVerifyOtp():Notifications.show("ERROR_OTP_INPUT");break;case CMD.PAYMENT_FIRST_PAY_UPDATE:this.listBonus1StPay=this._curPackage.listBonus1StPay,a=resourceMgr.getConfigChannelByChannelId(1).minRequire,a=playerModule.getGold()<a&&playerModule.getNumOfDailySupported()>=MAX_DAILY_SUPPORTED_GOLD,this.isContainBonus1StPay()&&(a||playerModule.getDayOld()>
DAY_OLD_CAN_SHOW_FIRST_PAY)&&!sceneMgr.isScene(GV.SCENE_IDS.TABLE)&&this.showGUIFirstPay()}}},createReceivedPackage:function(a,b){var c=null;switch(a){case CMD.PAYMENT_UPDATE:c=this.getInPacket(CmdReceivePaymentUpdate);break;case CMD.PAYMENT_IN_APP_PURCHASE_ANDROID:c=this.getInPacket(CmdReceiveIAPAndroid);break;case CMD.PAYMENT_IN_APP_PURCHASE_IOS:c=this.getInPacket(CmdReceiveIAPIOs);break;case CMD.PAYMENT_CREATE_TRANS:c=this.getInPacket(CmdReceivePaymentTrans);break;case CMD.PAYMENT_ZMP_SUBMIT_CARD:c=
this.getInPacket(CmdReceiveZMPSubmitCard);break;case CMD.PAYMENT_ZMP_REG_SMS:c=this.getInPacket(CmdReceiveZMPRegSMS);break;case CMD.PAYMENT_ZMP_GET_STATUS:c=this.getInPacket(CmdReceiveZMPGetStatus);break;case CMD.PAYMENT_SEA_VERIFY_OTP:c=this.getInPacket(CmdReceiveSeaVerifyOtp);break;case CMD.PAYMENT_FIRST_PAY_UPDATE:c=this.getInPacket(CmdReceiveFirstPayUpdate)}return c},getGUIIAP:function(){null==this._guiInAppPurchase&&(this._guiInAppPurchase=new GUIInAppPurchase,this._guiInAppPurchase.retain());
return this._guiInAppPurchase},getGUIStoreGold:function(){null==this._guiStoreGold&&(this._guiStoreGold=new GUIStoreGold,this._guiStoreGold.setVisible(!1),this._guiStoreGold.retain());return this._guiStoreGold},getLastPackIAP:function(){return this._lastPackIAP},getLastSMSPurchase:function(){return this._lastPackSMS},getPMCIDByTelcoChannel:function(a){switch(a){case TELCO_CHANNELS.ZING:return 1;case TELCO_CHANNELS.MOBI_PHONE:return 2;case TELCO_CHANNELS.VINA_PHONE:return 3;case TELCO_CHANNELS.VIETTEL:return 4}},
getSMSTransaction:function(a,b){this._curSMSTrans=new DataPaymentTrans;var c=servicesMgr.getCountry();c==COUNTRY.GOFA&&(c=COUNTRY.THAILAND);this._curSMSTrans.paymentSystem=b.partner;this._curSMSTrans.paymentType=b.paymentType;this._curSMSTrans.isWebView=b.isWebView;this._curSMSTrans.pinCode=b.phoneNumber?b.phoneNumber:"";this._curSMSTrans.needOtp=b.needOtp;if(0<this._curSMSTrans.paymentType){var d=playerModule.getPlayerInfo();this._curSMSTrans.telcoChannel=a.operator;this._curSMSTrans.countryId=c;
this._curSMSTrans.amount=a.cost;this._curSMSTrans.extraData=d.uName+":"+d.uId+":"+a.paymentItem;ZLog.error(".........."+JSON.stringify(this._curSMSTrans));this.sendGetPurchaseTransaction(this._curSMSTrans);c="&amount="+a.cost+"&currency="+PaymentUtils.getCurrency()+"&curOperator="+a.operator+"&phoneNumber="+this._curSMSTrans.pinCode;OpenTracker.track(TrackingAction.PURCHASE_SMS,c)}else Popups.showMessage("getSMSTransaction paymentType <= 0")},getTelcoTransaction:function(a){this._curCashCardTrans=
new DataPaymentTrans;var b=servicesMgr.getCountry();b==COUNTRY.GOFA&&(b=COUNTRY.THAILAND);this._curCashCardTrans.paymentSystem=a.partner;this._curCashCardTrans.paymentType=a.paymentType;this._curCashCardTrans.isWebView=a.isWebView;this._curCashCardTrans.countryId=b;this.sendGetPurchaseTransaction(this._curCashCardTrans)},hideGUIVerifyOtp:function(){this._guiVerifyOtp&&this._guiVerifyOtp.hide()},isPaymentByCard:function(a){return a==PAYMENT_CHANNELS.CARD||a==PAYMENT_CHANNELS.ZING_CARD||a==PAYMENT_CHANNELS.PRE_PAID_CARD},
isBonus1StPay:function(a){a=resourceMgr.getConfigSMSByKey(a);for(var b in this.listBonus1StPay){var c=this.listBonus1StPay[b].split("_")[1]-0;if(a.cost==c)return!1}return!0},isContainBonus1StPay:function(){var a=[],b;for(b in this.listBonus1StPay){var c=this.listBonus1StPay[b].split("_")[1]-0,c=resourceMgr.getConfigSMSByCost(PAYMENT_SYSTEM.CODA,c);null!=c&&a.push(c.cost)}b=PaymentResourceMgr.getConfigCODADCBPackAvailable();for(var d in b)if(!_.includes(a,b[d].cost))return!0;return!1},getMinBonus1StPay:function(){var a=
[],b;for(b in this.listBonus1StPay){var c=this.listBonus1StPay[b].split("_")[1]-0,c=resourceMgr.getConfigSMSByCost(PAYMENT_SYSTEM.CODA,c);null!=c&&a.push(c.cost)}b=PaymentResourceMgr.getConfigCODADCBPackAvailable();var c=[1],d;for(d in b)_.includes(a,b[d].cost)||c.push(b[d].bonus1StPay);return _.min(c)},addBonus1StPay:function(a){a=resourceMgr.getConfigSMSByKey(a);null!=a&&(a=servicesMgr.getCountry()+"_"+a.cost,_.includes(this.listBonus1StPay,a)||this.listBonus1StPay.push(a))},purchaseDCB:function(a,
b){void 0===b&&(b={});var c={paymentItem:PAYMENT_ITEMS.GOLD,operator:Operators.getCurrentOperator(),cost:a.cost,packId:a.packId,phoneNumber:"",isDCB:!0};b.hasOwnProperty("operator");c=_.assignWith(b,c,function(a,b){return _.isUndefined(a)?b:a});ZLog.debug("this.setLastSMSPurchase(purchaseInfo);"+JSON.stringify(c));this.setLastSMSPurchase(c);ZLog.debug("this.getGUIStoreGold().setCurrentDCBPack(dcbPack)"+JSON.stringify(a));this.getGUIStoreGold().setCurrentDCBPack(a);PaymentResourceMgr.getConfigPaymentDCBByOperator(servicesMgr.getCountry(),
this.operatorName);this.getSMSTransaction(c,listDCBPaymentType[0])},purchaseIAP:function(a,b){this.setLastPackIAP(a,b);fr.iap.payForProduct(a)},purchaseSMS:function(a,b){void 0===b&&(b={});var c={paymentItem:PAYMENT_ITEMS.GOLD,operator:Operators.getCurrentOperator(),cost:a.cost,packId:a.packId,phoneNumber:"",isDCB:!1},d=!b.hasOwnProperty("operator"),e=_.assignWith(b,c,function(a,b){return _.isUndefined(a)?b:a});this.setLastSMSPurchase(e);this.getGUIStoreGold().setCurrentSMSPack(a);if(servicesMgr.isEnablePayment(PAYMENT_SYSTEM.ZMPAY))this.sendGetRegSMS(e);
else{var c=function(){OpenTracker.track(TrackingAction.OPERATOR_CANNOT_DETECT);e.paymentItem==PAYMENT_ITEMS.GOLD?(paymentModule.getGUIStoreGold().isVisible()||paymentModule.getGUIStoreGold(),paymentModule.getGUIStoreGold().showSelectSMSOperator()):this._guiStoreItem?this._guiStoreItem.showSelectSMSOperator():ZLog.error("purchaseSMS: GUI store for this item not found: "+e.paymentItem)}.bind(this),f=servicesMgr.getCountry(),g=servicesMgr.getListPaymentMethods(),h=resourceMgr.getConfigPaymentSMS(f,e.operator,
g);if(0>h)if(h==PS_ERROR.OPERATOR_NOT_FOUND){f=resourceMgr.getConfigPaymentSMSDefault(f,g[0]);if(null==f){c();return}e.operator=f.operator;h=[f]}else{Popups.showMessage("CONFIG_NOT_FOUND");return}f=h;f[0].phoneNumber=e.phoneNumber;PaymentUtils.isSupportPostPaidAndPrePaid(f)?this.showGUIConfirmSMS(e.cost,f,function(a){this.getSMSTransaction(e,a)}.bind(this)):PaymentUtils.isNeedPhoneNumber(f[0])&&0==e.phoneNumber.length?d?c():this.showGUIInputPhoneNumber(e,f[0],function(a){this.getSMSTransaction(e,
a)}.bind(this)):servicesMgr.isConfirmSMS()?this.showGUIConfirmSMS(e.cost,f[0],function(a){this.getSMSTransaction(e,a)}.bind(this)):this.getSMSTransaction(e,f[0])}},purchaseTelco:function(a,b,c,d){void 0===d&&(d=PAYMENT_ITEMS.GOLD);var e=playerModule.getPlayerInfo(),e=e.uName+":"+e.uId+":"+d;a==TELCO_CHANNELS.VIETTEL||a==TELCO_CHANNELS.MOBI_PHONE||a==TELCO_CHANNELS.VINA_PHONE||a==TELCO_CHANNELS.ZING?(d=new DataZingCardTrans,d.pinCode=b,d.serial=c,d.embedData=e,d.pmcID=this.getPMCIDByTelcoChannel(a),
this.sendZMPSubmitCard(d)):(d=new DataPaymentTrans,d.telcoChannel=a,d.countryId=servicesMgr.getCountry(),d.amount=0,d.extraData=e,e=resourceMgr.getConfigPaymentTelco(d.countryId,a,servicesMgr.getListPaymentMethods()),0>e?Popups.showMessage("CANNOT_FIND_CONFIG"):(d.paymentSystem=e[0].partner,d.paymentType=e[0].paymentType,a==TELCO_CHANNELS.DTAC_HAPPY?(d.pinCode=c+b,d.serial=""):(d.pinCode=b,d.serial=c||""),this.sendGetPurchaseTransaction(d)))},resumeOTP:function(){var a=fr.UserData.getString(UserDataKey.TRANS_OTP_DATA,
"");if(a&&0<a.length)try{var b=JSON.parse(a);b&&!b.hasOwnProperty("empty")&&paymentModule.showGUIVerifyOtp(b.paymenttype,b.transid,b.partnertransid)}catch(c){ZLog.error("trans OTP data parse error: "+c.message)}},sendGetPurchaseTransaction:function(a){sceneMgr.showGUIWaiting();ZLog.debug("CREATE_TRANS | %s",JSON.stringify(a));a=this.getOutPacket(CmdSendPaymentTrans,a);this.send(a)},sendGetRegSMS:function(a){if(Operators.isOperator(TELCO_CHANNELS.VIETTEL)||Operators.isOperator(TELCO_CHANNELS.VINA_PHONE)||
Operators.isOperator(TELCO_CHANNELS.MOBI_PHONE)){sceneMgr.showGUIWaiting();var b=playerModule.getPlayerInfo(),b={platform:fr.platformWrapper.getOsName(),embedData:b.uName+":"+b.uId+":"+a.paymentItem,amount:a.cost,netWorkOperation:Operators.getCurrentMCCMNC()};a="&amount="+a.cost+"&currency="+PaymentUtils.getCurrency()+"&curOperator="+Operators.getCurrentOperator();OpenTracker.track(TrackingAction.PURCHASE_SMS,a);a=this.getOutPacket(CmdSendZMPRegSMS,b);this.send(a)}else OpenTracker.track(TrackingAction.OPERATOR_CANNOT_DETECT),
null!=this._guiStoreItem&&this._guiStoreItem.isVisible()?this._guiStoreItem.showSelectSMSOperator():this._guiStoreGold&&this._guiStoreGold.isVisible()?this._guiStoreGold.showSelectSMSOperator():Popups.showMessage(languageMgr.getString("NOTIFICATION_PAYMENT_TYPE_NOT_FOUND").replace("@value",fr.platformWrapper.getNetworkOperator()))},sendIAPAndroid:function(a){ZLog.debug("sendIAPAndroid:"+JSON.stringify(a)+", type = "+this._lastPackIAP.type);a=this.getOutPacket(CmdSendIAPAndroid,a,this._lastPackIAP.type);
this.send(a)},sendIAPIOS:function(a){ZLog.debug("sendIAPIOS:"+a+", type = "+this._lastPackIAP.type);a=this.getOutPacket(CmdSendIAPIOs,a,this._lastPackIAP.type);this.send(a)},sendSMS:function(a){switch(this._curSMSTrans.paymentSystem){case PAYMENT_SYSTEM.CODA:var b=fr.coda.createSMS(this._curSMSTrans.amount,this._curSMSTrans.telcoChannel,a.instruction);if(b){b.phoneNo?Popups.showMessage(a.instruction,function(){fr.platformWrapper.sendSMS(b.phoneNo,b.msg)}):Popups.showMessage(b);return}break;case PAYMENT_SYSTEM.BLUE_PAY:b=
fr.bluepay.createSMS(this._curSMSTrans.amount,this._curSMSTrans.telcoChannel,a.transId);break;case PAYMENT_SYSTEM.MOL:b=fr.mol.createSMS(this._curSMSTrans.amount,this._curSMSTrans.telcoChannel,a.transId);break;case PAYMENT_SYSTEM.IPAYY:b=fr.ipayy.createSMS(a.shortCode,a.message)}b?fr.platformWrapper.sendSMS(b.phoneNo,b.msg):ZLog.debug("SMS Data null")},sendVerifyOtpSea:function(a,b,c,d){ZLog.debug("send sendVerifyOtp: %s %s %s %s",a,b,c,d);OpenTracker.track(TrackingAction.PURCHASE_SMS,"&otp="+d+"&paymentType="+
a);a=this.getOutPacket(CmdSendVerifyOtpSea,{paymentType:a,transId:b,partnerTransId:c,otp:d});this.send(a)},sendZMPGetStatus:function(a){ZLog.debug("send sendZMPGetStatus: %s",a);a=this.getOutPacket(CmdSendZMPGetStatus,a);this.send(a)},sendZMPSubmitCard:function(a){sceneMgr.showGUIWaiting();var b=playerModule.getPlayerInfo();a.platform=fr.platformWrapper.getOsName();a.embedData=b.uName+":"+b.uId;ZLog.debug("sendZMPSubmitCard: %s",JSON.stringify(a));a=this.getOutPacket(CmdSendZMPSubmitCard,a);this.send(a)},
sendFirstPayUpdate:function(){ZLog.debug("send pay ment 1st bonus");var a=this.getOutPacket(CmdSendFirstPayUpdate);this.send(a)},setCurrentSMSTransData:function(a){this._curSMSTrans=a},setGUIStoreItem:function(a){this._guiStoreItem=a},setLastPackIAP:function(a,b){this._lastPackIAP.pack=a;this._lastPackIAP.type=b},setLastSMSPurchase:function(a){this._lastPackSMS=a},showGUIFirstPay:function(){null==this._guiFirstPay&&(this._guiFirstPay=new GUIFirstP,this._guiFirstPay.setVisible(!1),this._guiFirstPay.retain());
this._guiFirstPay.showAtCurrentScene()},showGetTransError:function(a){Popups.showMessage("ERROR_CODE_TRANS_"+Math.abs(a))},showGUIConfirmSMS:function(a,b,c){null==this._guiConfirmSMS&&(this._guiConfirmSMS=new GUIConfirmSMS,this._guiConfirmSMS.retain());this._guiConfirmSMS.setData({amount:a,paymentTypeData:b,callback:c});this._guiConfirmSMS.showAtCurrentScene(Z_ORDER.PAYMENT_GUI+2)},showGUIIAP:function(){this.getGUIIAP();this._guiInAppPurchase.showAtCurrentScene(Z_ORDER.PAYMENT_GUI)},showGUIInputPhoneNumber:function(a,
b,c){null==this._guiInputPhoneNumber&&(this._guiInputPhoneNumber=new GUIInputPhoneNumber,this._guiInputPhoneNumber.retain());this._guiInputPhoneNumber.setData({purchaseInfo:a,paymentTypeData:b,callback:c});this._guiInputPhoneNumber.showAtCurrentScene(Z_ORDER.PAYMENT_GUI+2)},showGUIPurchase:function(){var a=servicesMgr.getEnablePaymentSystem()+"&level="+playerModule.getLevel()+"&vipLevel="+playerModule.getVipLevel()+"&installDate="+servicesMgr.getInstallDate();OpenTracker.track(TrackingAction.PAYMENT_SYSTEM,
a);servicesMgr.isOnlyEnablePayment(PAYMENT_SYSTEM.IAP)?this.showGUIIAP():(a=this.showGUIStoreGold(),servicesMgr.isEnablePayment(PAYMENT_SYSTEM.ZMPAY)?a.selectChannelStore(ChannelStore.CASH_CARD):PaymentUtils.isLocalSMSSupported(servicesMgr.getCountry(),servicesMgr.getListPaymentMethods())?a.selectChannelStore(ChannelStore.SMS):servicesMgr.isEnablePayment(PAYMENT_SYSTEM.IAP)?a.selectChannelStore(PlatformUtils.isIOs()?ChannelStore.IAP_IOS:ChannelStore.IAP_Android):PaymentUtils.isLocalDCBSupported(servicesMgr.getCountry(),
servicesMgr.getListPaymentMethods())&&a.selectChannelStore(ChannelStore.DCB))},showGUIStoreGold:function(){this.getGUIStoreGold().showAtCurrentScene(Z_ORDER.PAYMENT_GUI);return this._guiStoreGold},showGUIVerifyOtp:function(a,b,c){null==this._guiVerifyOtp&&(this._guiVerifyOtp=new GUIVerifyOtp,this._guiVerifyOtp.retain());this._guiVerifyOtp.setData({paymenttype:a,transid:b,partnertransid:c});this._guiVerifyOtp.showAtCurrentScene(Z_ORDER.PAYMENT_GUI+2)},showZMPError:function(a,b){switch(a){case ZING_CARD_CODE.SUCCESS:break;
case ZING_CARD_CODE.IN_PROCESSING:if(null!=b&&""!=b){var c=GameUtils.getPerfectText(b,res.UTM_AVO_P13_BOLD,30,505,cc.TEXT_ALIGNMENT_CENTER,cc.VERTICAL_TEXT_ALIGNMENT_CENTER);Popups.showMessage(c)}else Popups.showMessage("ZING_PAYMENT_IN_PROCESS");break;default:null!=b&&""!=b?(c=GameUtils.getPerfectText(b,res.UTM_AVO_P13_BOLD,30,505,cc.TEXT_ALIGNMENT_CENTER,cc.VERTICAL_TEXT_ALIGNMENT_CENTER),Popups.showMessage(c)):Popups.showMessage("ZING_PAYMENT_FAIL")}},updateStoreGold:function(){this._guiStoreGold&&
this._guiStoreGold.isVisible()&&this._guiStoreGold.updateStoreGold()},isFreeTime:function(){if(!FREE_TIME_TO_ENABLE_TELCO)return!1;var a=new Date(Utility.getClientTimeInMilliseconds()),b=a.getDay(),a=a.getHours();return 0<=a&&7>=a||12==a||22==a?!0:(0==b||6==b)&&(9<=a&&13>=a||20<=a&&23>=a)}}),PaymentResourceMgr=ResourcesMgr.prototype;PaymentResourceMgr.getNumOfGPack=_.memoize(function(){return resourceMgr.getConfigBaseGoldPacks().length});
PaymentResourceMgr.getConfigGPackNearest=function(a){for(var b=resourceMgr.getConfigBaseGoldPacks(),c=-1,d=0;d<b.length;++d)if(b[d].xuCost>a){c=0==d?0:d-1;break}0>c&&(c=b.length-1);return b[c]};PaymentResourceMgr.getConfigGPack=_.memoize(function(a){var b=resourceMgr.getJson(res_jsons.GoldPack);return _.assign(new ConfigGPack,b.BasePack[a])});
PaymentResourceMgr.getConfigBaseGoldPacks=_.memoize(function(){var a=_.map(resourceMgr.getJson(res_jsons.GoldPack).BasePack,function(a,c){a.packId=c;return a});return _.filter(a,function(a){return"GP_0"!=a.packId})});PaymentResourceMgr.getConfigZaloSMSPackAvailable=_.memoize(function(){var a=_.map(resourceMgr.getJson(res_jsons.GoldPack).ZaloSMSPack,function(a,c){a.packId=c;return a});return _.filter(a,function(a){return a.isAvailable})});
PaymentResourceMgr.getConfigZMPSMSPackAvailable=_.memoize(function(){var a=_.map(resourceMgr.getJson(res_jsons.GoldPack).ZingSMSPack,function(a,c){a.packId=c;return a});return _.filter(a,function(a){return a.isAvailable})});PaymentResourceMgr.getConfigBluePaySMSPackAvailable=_.memoize(function(){var a=_.map(resourceMgr.getJson(res_jsons.GoldPack).BluePaySMSPackTH,function(a,c){a.packId=c;return a});return _.filter(a,function(a){return a.isAvailable})});
PaymentResourceMgr.getConfigMOLSMSPackAvailable=_.memoize(function(){if(servicesMgr.getCountry()==COUNTRY.MYANMAR)var a=resourceMgr.getJson(res_jsons.GoldPack).MOL_MM;a=_.map(a,function(a,c){a.packId=c;return a});return _.filter(a,function(a){return a.isAvailable})},function(){return _.join([servicesMgr.getCountry(),_.join(servicesMgr.getListPaymentMethods())])});
PaymentResourceMgr.getConfigCODADCBPackAvailable=_.memoize(function(){var a;servicesMgr.getCountry()==COUNTRY.MYANMAR&&(a=resourceMgr.getJson(res_jsons.GoldPack).CODA_MM);a=_.map(a,function(a,c){a.packId=c;return a});return _.filter(a,function(a){return a.isAvailable})},function(){return _.join([servicesMgr.getCountry(),_.join(servicesMgr.getListPaymentMethods())])});
PaymentResourceMgr.getConfigCODASMSPackAvailable=_.memoize(function(){var a=resourceMgr.getJson(res_jsons.GoldPack).CODASMSPackMM,a=_.map(a,function(a,c){a.packId=c;return a});return _.filter(a,function(a){return a.isAvailable})},function(){return _.join([servicesMgr.getCountry(),_.join(servicesMgr.getListPaymentMethods())])});
PaymentResourceMgr.getConfigIpayySMSPackAvailable=_.memoize(function(){var a=resourceMgr.getJson(res_jsons.GoldPack).IPAYYSMSPackIN,a=_.map(a,function(a,c){a.packId=c;return a});return _.filter(a,function(a){return a.isAvailable})});PaymentResourceMgr.getConfigIpayyDCBPackAvailable=_.memoize(function(){var a=resourceMgr.getJson(res_jsons.GoldPack).IPAYYDCBPackIN,a=_.map(a,function(a,c){a.packId=c;return a});return _.filter(a,function(a){return a.isAvailable})});
PaymentResourceMgr.getConfigFortumoSMSPackAvailable=_.memoize(function(){var a=resourceMgr.getJson(res_jsons.GoldPack).FORTSMSPackIN,a=_.map(a,function(a,c){a.packId=c;return a});return _.filter(a,function(a){return a.isAvailable})});
PaymentResourceMgr.getConfigSMSByKey=function(a){var b=resourceMgr.getConfigSMSPack(),c;for(c in b)for(var d=0;d<b[c].length;++d)if(a==b[c][d].packId)return b[c][d];b=resourceMgr.getConfigDCBPack();for(c in b)for(d=0;d<b[c].length;++d)if(a==b[c][d].packId)return b[c][d];ZLog.error("not found or not loaded SMSByKey or DCBByKey: %s",a);return null};PaymentResourceMgr.getConfigSMSByCost=_.memoize(function(a,b){var c=resourceMgr.getConfigSMSPack()[a];return _.find(c,function(a){return a.cost==b})},function(){return _.join(arguments)});
PaymentResourceMgr.getConfigIAPPacks=_.memoize(function(){var a=resourceMgr.getJson(res_jsons.InAppPurchase).InAppPurchase,a=_.map(a,function(a,c){return{gold:a.gold,usdCost:a.usdCost,localeCost:a.localeCost,vPoint:a.vPoint,productId:c}});return _(a).map(function(a,c){a.index=c;return a}).orderBy(["gold"],["desc"]).value()});
PaymentResourceMgr.getConfigIAPPackByProductId=_.memoize(function(a){ZLog.debug("getConfigIAPPackByProductId: "+a);return _.find(resourceMgr.getConfigIAPPacks(),function(b){return 0<=a.indexOf(b.productId)})});
PaymentResourceMgr.getConfigSMSPack=function(){var a={};servicesMgr.isEnablePayment(PAYMENT_SYSTEM.BLUE_PAY)&&(a[PAYMENT_SYSTEM.BLUE_PAY]=resourceMgr.getConfigBluePaySMSPackAvailable());servicesMgr.isEnablePayment(PAYMENT_SYSTEM.MOL)&&(a[PAYMENT_SYSTEM.MOL]=resourceMgr.getConfigMOLSMSPackAvailable());servicesMgr.isEnablePayment(PAYMENT_SYSTEM.CODA)&&(a[PAYMENT_SYSTEM.CODA]=resourceMgr.getConfigCODASMSPackAvailable());servicesMgr.isEnablePayment(PAYMENT_SYSTEM.ZMPAY)&&(a[PAYMENT_SYSTEM.ZMPAY]=resourceMgr.getConfigZMPSMSPackAvailable());
servicesMgr.isEnablePayment(PAYMENT_SYSTEM.ZALO)&&(a[PAYMENT_SYSTEM.ZALO]=resourceMgr.getConfigZaloSMSPackAvailable());servicesMgr.isEnablePayment(PAYMENT_SYSTEM.IPAYY)&&(a[PAYMENT_SYSTEM.IPAYY]=resourceMgr.getConfigIpayySMSPackAvailable());return a};
PaymentResourceMgr.getConfigDCBPack=function(){var a={};servicesMgr.isEnablePayment(PAYMENT_SYSTEM.CODA)&&(a[PAYMENT_SYSTEM.CODA]=resourceMgr.getConfigCODADCBPackAvailable());servicesMgr.isEnablePayment(PAYMENT_SYSTEM.MOL)&&(a[PAYMENT_SYSTEM.MOL]=resourceMgr.getConfigMOLSMSPackAvailable());servicesMgr.isEnablePayment(PAYMENT_SYSTEM.IPAYY)&&(a[PAYMENT_SYSTEM.IPAYY]=resourceMgr.getConfigIpayyDCBPackAvailable());return a};
PaymentResourceMgr.getConfigFirstSMSPack=function(){var a=resourceMgr.getConfigSMSPack();if(servicesMgr.isEnablePayment(PAYMENT_SYSTEM.ZMPAY))return _.nth(a[PAYMENT_SYSTEM.ZMPAY],-1);if(servicesMgr.isEnablePayment(PAYMENT_SYSTEM.CODA))return a[PAYMENT_SYSTEM.CODA][0];if(servicesMgr.isEnablePayment(PAYMENT_SYSTEM.MOL))return a[PAYMENT_SYSTEM.MOL][0];if(servicesMgr.isEnablePayment(PAYMENT_SYSTEM.BLUE_PAY))return a[PAYMENT_SYSTEM.BLUE_PAY][0];if(servicesMgr.isEnablePayment(PAYMENT_SYSTEM.IPAYY))return _.find(a[PAYMENT_SYSTEM.IPAYY],
function(a){return 14<a.cost});ZLog.error("not found or not loaded getConfigFirstSMSPack: %s");return null};PaymentResourceMgr.getConfigBluePayPhoneNoSMSByAmount=_.memoize(function(a,b){if(b&&0<b.length){b==TELCO_CHANNELS.TRUE&&(b+="money");b=b.toUpperCase();var c=resourceMgr.getJson(res_jsons.GoldPack).BluePaySMSPackTH,d;for(d in c)if(c[d].cost==a)for(var e in c[d].skull)if(b==e)return c[d].skull[b]}return""},function(){return _.join(arguments)});
PaymentResourceMgr.getConfigMOLPhoneNoSMSByAmount=_.memoize(function(a,b){if(b&&0<b.length){b==TELCO_CHANNELS.TRUE&&(b+="money");b=b.toUpperCase();var c=servicesMgr.getCountry();if(c==COUNTRY.INDO)var d=resourceMgr.getJson(res_jsons.GoldPack).MOLSMSPackID;else c==COUNTRY.THAILAND||c==COUNTRY.GOFA?d=resourceMgr.getJson(res_jsons.GoldPack).MOLSMSPackTH:c==COUNTRY.MALAYSIA&&(d=resourceMgr.getJson(res_jsons.GoldPack).MOLSMSPackMY);if(c=_.find(d,function(b){return b.cost==a}))if(c=_.find(c.skull,function(a,
c){return c==b}))return c}return""},function(){return _.join(arguments)});PaymentResourceMgr.getConfigMOLCodeSMSByAmount=_.memoize(function(a){var b=servicesMgr.getCountry();if(b==COUNTRY.INDO)b=resourceMgr.getJson(res_jsons.GoldPack).MOLSMSPackID;else if(b==COUNTRY.MALAYSIA)b=resourceMgr.getJson(res_jsons.GoldPack).MOLSMSPackMY;else return"";for(var c in b)if(b[c].cost==a)return b[c].code;return""});
PaymentResourceMgr.getConfigCardByKey=_.memoize(function(a){for(var b=resourceMgr.getConfigAllCardPacks(),c=0;c<b.length;++c)if(a==b[c].packId)return b[c];ZLog.error("not found or not loaded cardByKey: %s",a);return null});PaymentResourceMgr.getConfigAllCardPacks=_.memoize(function(){return _.flatten(_.map(resourceMgr.getJson(res_jsons.CardGoldPack),function(a){return _.map(a,function(a,c){a.packId=c;return a})}))});
PaymentResourceMgr.getConfigCardGoldPacks=function(a){var b=[];servicesMgr.isEnablePayment(PAYMENT_SYSTEM.ZMPAY)?b=resourceMgr.getConfigZMPCardGoldPacks():servicesMgr.isEnablePayment(PAYMENT_SYSTEM._2C2P)?b=resourceMgr.getConfig2C2PCardGoldPacks():servicesMgr.isEnablePayment(PAYMENT_SYSTEM.MOL)?b=resourceMgr.getConfigMOLCardGoldPacks():servicesMgr.isEnablePayment(PAYMENT_SYSTEM.BLUE_PAY)&&(b=resourceMgr.getConfigBluePayCardGoldPacks());void 0!==a&&(a=a.toUpperCase(),"TRUE"==a&&(a="TRUEMONEY"),b=_.filter(b,
function(b){return b.isAvailable.hasOwnProperty(a)&&b.isAvailable[a]}));return _(b).map(function(a,b){a.index=b;return a}).orderBy(["gold"],["desc"]).value()};PaymentResourceMgr.getConfigZMPCardGoldPacks=_.memoize(function(){return _.map(resourceMgr.getJson(res_jsons.CardGoldPack).ZaloCardPack,function(a,b){a.packId=b;return a})});
PaymentResourceMgr.getConfigMOLCardGoldPacks=_.memoize(function(){switch(servicesMgr.getCountry()){case COUNTRY.THAILAND:var a="MOLCardPackTH";break;case COUNTRY.MALAYSIA:a="MOLCardPackMY";break;case COUNTRY.INDO:a="MOLCardPackID";break;default:return[]}return _.map(resourceMgr.getJson(res_jsons.CardGoldPack)[a],function(a,c){a.packId=c;return a})});
PaymentResourceMgr.getConfigBluePayCardGoldPacks=_.memoize(function(){return _.map(resourceMgr.getJson(res_jsons.CardGoldPack).BluePayCardPackTH,function(a,b){a.packId=b;return a})});PaymentResourceMgr.getConfig2C2PCardGoldPacks=_.memoize(function(){return _.map(resourceMgr.getJson(res_jsons.CardGoldPack)["2C2P_MM"],function(a,b){a.packId=b;return a})});
PaymentResourceMgr.getConfigPaymentSMSDefault=function(a,b){var c=resourceMgr.getJson(res_jsons.PS).country[a];if(null==c||null==c.sms)return null;c=c.sms["default"];if(null==c||!_.isArray(c)||0==c.length)return null;for(var d=0;d<c.length;++d)if(c[d].partner==b)return ZLog.debug("configByOperator default = "+JSON.stringify(c[d])),c[d];return null};
PaymentResourceMgr.getConfigPaymentDCBByOperator=function(a,b){var c=resourceMgr.getJson(res_jsons.PS).country[a];if(null==c)return ZLog.error("getConfigPaymentSMSByOperator CANNOT find this COUNTRY config for: "+JSON.stringify(arguments)),PS_ERROR.COUNTRY_NOT_FOUND;c=c.dcb[b];return null==c?(ZLog.error("getConfigPaymentSMSByOperator CANNOT find this OPERATOR config for: "+JSON.stringify(arguments)),PS_ERROR.OPERATOR_NOT_FOUND):c=_.orderBy(c,["priority"],["desc"])};
PaymentResourceMgr.getConfigPaymentSMSByOperator=function(a,b){var c=resourceMgr.getJson(res_jsons.PS).country[a];if(null==c)return ZLog.error("getConfigPaymentSMSByOperator CANNOT find this COUNTRY config for: "+JSON.stringify(arguments)),PS_ERROR.COUNTRY_NOT_FOUND;c=c.sms[b];return null==c?(ZLog.error("getConfigPaymentSMSByOperator CANNOT find this OPERATOR config for: "+JSON.stringify(arguments)),PS_ERROR.OPERATOR_NOT_FOUND):c=_.orderBy(c,["priority"],["desc"])};
PaymentResourceMgr.getConfigPaymentTelcoByTelcoChannel=function(a,b){var c=resourceMgr.getJson(res_jsons.PS).country[a];if(null==c)return ZLog.error("getConfigPaymentTelcoByTelcoChannel CANNOT find this COUNTRY config for: "+JSON.stringify(arguments)),PS_ERROR.COUNTRY_NOT_FOUND;c=c.telco[b];return null==c?(ZLog.error("getConfigPaymentTelcoByTelcoChannel CANNOT find this TELCO CHANNEL config for: "+JSON.stringify(arguments)),PS_ERROR.OPERATOR_NOT_FOUND):c=_.orderBy(c,["priority"],["desc"])};
PaymentResourceMgr.getConfigPaymentDCB=function(a,b,c){if(3!=arguments.length)return ZLog.error("getConfigPaymentSMS require 3 args: "+JSON.stringify(arguments)),PS_ERROR.PARAM_INVALID;var d=this.getConfigPaymentDCBByOperator(a,b);if(0>d)return d;for(var e=_.isArray(c)?c:[c],f=[],g=0;g<d.length;++g)for(var h=0;h<e.length;++h)d[g].partner==e[h]&&f.push(d[g]);return 0==f.length?(ZLog.error("getConfigPaymentSMS require PAYMENT_TYPE_NOT_FOUND:"+JSON.stringify(arguments)),PS_ERROR.PAYMENT_TYPE_NOT_FOUND):
f};PaymentResourceMgr.getConfigPaymentSMS=function(a,b,c){if(3!=arguments.length)return ZLog.error("getConfigPaymentSMS require 3 args: "+JSON.stringify(arguments)),null;var d=this.getConfigPaymentSMSByOperator(a,b);if(0>d)return d;for(var e=_.isArray(c)?c:[c],f=[],g=0;g<d.length;++g)for(var h=0;h<e.length;++h)d[g].partner==e[h]&&f.push(d[g]);return 0==f.length?(ZLog.error("getConfigPaymentSMS require PAYMENT_TYPE_NOT_FOUND:"+JSON.stringify(arguments)),PS_ERROR.PAYMENT_TYPE_NOT_FOUND):f};
PaymentResourceMgr.getConfigPaymentTelco=function(a,b,c){if(3!=arguments.length)return ZLog.error("getConfigPaymentTelco require 3 args: "+JSON.stringify(arguments)),null;var d=this.getConfigPaymentTelcoByTelcoChannel(a,b);if(0>d)return d;for(var e=_.isArray(c)?c:[c],f=[],g=0;g<d.length;++g)for(var h=0;h<e.length;++h)d[g].partner==e[h]&&f.push(d[g]);return 0==f.length?(ZLog.error("getConfigPaymentTelco require PAYMENT_TYPE_NOT_FOUND:"+JSON.stringify(arguments)),PS_ERROR.PAYMENT_TYPE_NOT_FOUND):f};
PaymentResourceMgr.getRecommendedPurchaseForDeal=function(a){var b=resourceMgr.getConfigSMSPack(),c=resourceMgr.getConfigDCBPack(),d=null;a==ExclusiveDealId.DEAL_1?servicesMgr.isEnablePayment(PAYMENT_SYSTEM.ZALO)?d=b[PAYMENT_SYSTEM.ZALO][0]:servicesMgr.isEnablePayment(PAYMENT_SYSTEM.ZMPAY)?d=b[PAYMENT_SYSTEM.ZMPAY][0]:servicesMgr.isEnablePayment(PAYMENT_SYSTEM.MOL)?d=b.hasOwnProperty(PAYMENT_SYSTEM.MOL)?b[PAYMENT_SYSTEM.MOL][0]:c[PAYMENT_SYSTEM.MOL][0]:servicesMgr.isEnablePayment(PAYMENT_SYSTEM.BLUE_PAY)?
d=b[PAYMENT_SYSTEM.BLUE_PAY][0]:servicesMgr.isEnablePayment(PAYMENT_SYSTEM.CODA)?d=c[PAYMENT_SYSTEM.CODA][0]:servicesMgr.isEnablePayment(PAYMENT_SYSTEM.IPAYY)?d=b.hasOwnProperty(PAYMENT_SYSTEM.IPAYY)?b[PAYMENT_SYSTEM.IPAYY][0]:c[PAYMENT_SYSTEM.IPAYY][0]:servicesMgr.isEnablePayment(PAYMENT_SYSTEM.IAP)&&(a=resourceMgr.getConfigIAPPackByProductId(iapProductList[0]),d={gold:a.gold,cost:a.usdCost,vPoint:a.vPoint,packId:iapProductList[0]}):a==ExclusiveDealId.DEAL_2&&(servicesMgr.isEnablePayment(PAYMENT_SYSTEM.ZALO)?
d=_.nth(b[PAYMENT_SYSTEM.ZALO],-1):servicesMgr.isEnablePayment(PAYMENT_SYSTEM.ZMPAY)?d=_.nth(b[PAYMENT_SYSTEM.ZMPAY],-1):servicesMgr.isEnablePayment(PAYMENT_SYSTEM.MOL)?d=b.hasOwnProperty(PAYMENT_SYSTEM.MOL)?b[PAYMENT_SYSTEM.MOL][1]:c[PAYMENT_SYSTEM.MOL][0]:servicesMgr.isEnablePayment(PAYMENT_SYSTEM.BLUE_PAY)?d=b[PAYMENT_SYSTEM.BLUE_PAY][1]:servicesMgr.isEnablePayment(PAYMENT_SYSTEM.CODA)?d=_.find(c[PAYMENT_SYSTEM.CODA],function(a){return 900<=a.cost}):servicesMgr.isEnablePayment(PAYMENT_SYSTEM.IPAYY)?
d=b.hasOwnProperty(PAYMENT_SYSTEM.IPAYY)?b[PAYMENT_SYSTEM.IPAYY][0]:c[PAYMENT_SYSTEM.IPAYY][0]:servicesMgr.isEnablePayment(PAYMENT_SYSTEM.IAP)&&(a=resourceMgr.getConfigIAPPackByProductId(iapProductList[0]),d={gold:a.gold,cost:a.usdCost,vPoint:a.vPoint,packId:iapProductList[0]}));b=null;return d};
PaymentResourceMgr.getConfigIAPPortalPacks=_.memoize(function(){var a=fr.platformWrapper.getPackageName(),b=resourceMgr.getJson(res_jsons.InAppPurchase).packResolver,c=[],d;for(d in b)for(var e=0,f=b[d].packageName.length;e<f;++e)b[d].packageName[e]==a&&(b[d].packId=d,c.push(b[d]));return _(c).uniqBy("target").map(function(a){return a.packId}).value()});
PaymentResourceMgr.getConfigIAPPortalPackIdByPackId=_.memoize(function(a){var b=fr.platformWrapper.getPackageName(),c=resourceMgr.getJson(res_jsons.InAppPurchase).packResolver;if(c)for(var d in c)for(var e=0,f=c[d].packageName.length;e<f;++e)if(a==c[d].target&&b==c[d].packageName[e])return d;return""});PaymentResourceMgr.getConfigIAPPackIdByIAPPortalPackId=_.memoize(function(a){return(a=resourceMgr.getJson(res_jsons.InAppPurchase).packResolver[a])?a.target:""});
var PaymentUtils=function(){return{isWebViewType:function(a){return a.isWebView},isNeedPhoneNumber:function(a){return a&&a.needPhoneNumber},isSupportPostPaidAndPrePaid:function(a){if(1==a.length)return!1;for(var b=!1,c=!1,d=0;d<a.length;++d)a[d].canPostpaid?c=!0:b=!0;return b&&c},isLocalPaymentSystemSupported:function(a){for(var b=resourceMgr.getJson(res_jsons.PS).paymentSystems,c=0;c<b.length;++c)if(b[c]==a)return!0;return!1},isLocalDCBSupported:function(a,b){var c=resourceMgr.getJson(res_jsons.PS).country[a];
if(null==c)return!1;for(var d in c.dcb)for(var e=c.dcb[d],f=0;f<e.length;++f)for(var g=0;g<b.length;++g)if(e[f].partner==b[g])return!0;return!1},isLocalSMSSupported:function(a,b){var c=resourceMgr.getJson(res_jsons.PS).country[a];if(null==c)return!1;for(var d in c.sms)for(var e=c.sms[d],f=0;f<e.length;++f)for(var g=0;g<b.length;++g)if(e[f].partner==b[g])return!0;return!1},isLocalTelcoSupported:function(a,b){return 0<this.getListTelcoChannel(a,b).length},isValidCardInputFormat:function(a,b,c){if(b==
c)return!1;switch(a){case TELCO_CHANNELS.DTAC_HAPPY:case TELCO_CHANNELS.MOL_POINTS:return CARD_REG[a].PIN_CODE.test(b)&&CARD_REG[a].SERIAL.test(c);case TELCO_CHANNELS.TRUE:case TELCO_CHANNELS.AIS:case TELCO_CHANNELS.EASY_POINTS:return CARD_REG[a].PIN_CODE.test(b)}return!0},getPrePaid:function(a){for(var b=0;b<a.length;++b)if(!a[b].canPostpaid)return a[b];return null},getPostPaid:function(a){for(var b=0;b<a.length;++b)if(a[b].canPostpaid)return a[b];return null},getCurrency:function(){switch(servicesMgr.getCountry()){case COUNTRY.VIETNAM:return CURRENCY.VND;
case COUNTRY.INDO:return CURRENCY.IDR;case COUNTRY.MALAYSIA:return CURRENCY.MYR;case COUNTRY.THAILAND:case COUNTRY.GOFA:return CURRENCY.THB;case COUNTRY.MYANMAR:return CURRENCY.MMK;case COUNTRY.INDIA:return CURRENCY.INR;default:return CURRENCY.USD}},getAvailableOperators:_.memoize(function(a,b,c){void 0===c&&(c=!1);var d=resourceMgr.getJson(res_jsons.PS).country[a];if(null==d)return[];a=[];c=c?d.dcb:d.sms;for(var e in c)if("default"!=e)for(var d=c[e],f=0;f<d.length;++f)for(var g=0;g<b.length;++g)if(d[f].partner==
b[g]){a.push(e);break}return a=_.uniq(a)},function(){return _.join(arguments)}),getListTelcoChannel:_.memoize(function(a,b){var c=resourceMgr.getJson(res_jsons.PS).country[a];if(null==c)return ZLog.error("getListTelcoChannel CANNOT find this COUNTRY config for: "+JSON.stringify(arguments)),[];var d=[],e;for(e in c.telco)for(var f=c.telco[e],g=0;g<f.length;++g)for(var h=0;h<b.length;++h)if(f[g].partner==b[h]){d.push(e);break}return d=_.uniq(d)},function(){return _.join(arguments)}),getSMSTotalGold:_.memoize(function(a){var b=
resourceMgr.getConfigSMSByKey(a),c=0;b&&(c=PaymentUtils.getSMSPercentBonus(a)*b.gold);return c},function(a){var b=eventModule.getEventById(EVENT_ID.FIRST_TIME),c=playerModule.getVipLevel(),b=b.hasEventInfo()&&b.isFirstSMSAvailable()?"1":"0",d=eventModule.getSpecialEventById(SPECIAL_EVENT_ID.PURCHASE_PROMOTION).isAvailable()?"1":"0";return a+"_"+c+b+d}),getTelcoTotalGold:_.memoize(function(a){var b=resourceMgr.getConfigCardByKey(a),c=0;if(b){a=PaymentUtils.getTelcoPercentBonus(a);var c=resourceMgr.getConfigMyVIP(),
c=b.gold*(1+c.buyGoldBonusRate),d=eventModule.getSpecialEventById(EVENT_ID.EXCLUSIVE_DEALS),c=d.hasEventInfo()&&d.canCompleteDeal(c)?0:1,d=eventModule.getSpecialEventById(SPECIAL_EVENT_ID.PURCHASE_PROMOTION).isAvailable()?1+resourceMgr.getConfigPurchasePromotionPercent():1,c=a*b.gold+c*resourceMgr.getConfigEventFirstTimeCardBonus()*d}return c},function(){var a=eventModule.getEventById(EVENT_ID.FIRST_TIME),b=playerModule.getVipLevel(),a=a.hasEventInfo()&&a.isFirstCashCardAvailable()?"1":"0",c=eventModule.getSpecialEventById(SPECIAL_EVENT_ID.PURCHASE_PROMOTION).isAvailable()?
"1":"0",d="";if(0<arguments.length){var e=arguments[0],f=resourceMgr.getConfigMyVIP();if(e=resourceMgr.getConfigCardByKey(e))d=e.gold*(1+f.buyGoldBonusRate),f=eventModule.getSpecialEventById(EVENT_ID.EXCLUSIVE_DEALS),d=f.hasEventInfo()&&f.canCompleteDeal(d)?"1":"0"}return arguments[0]+"_"+b+a+c+d}),getIAPTotalGold:_.memoize(function(a){var b=resourceMgr.getConfigIAPPackByProductId(a),c=0;b&&(c=PaymentUtils.getIAPPercentBonus(a)*b.gold);return c},function(a){var b=eventModule.getEventById(EVENT_ID.FIRST_TIME),
c=playerModule.getVipLevel(),b=b.hasEventInfo()&&b.isFirstIAPAvailable()?"1":"0",d=eventModule.getSpecialEventById(SPECIAL_EVENT_ID.PURCHASE_PROMOTION).isAvailable()?"1":"0";return a+"_"+c+b+d}),getSMSPercentBonus:_.memoize(function(a){var b=eventModule.getEventById(EVENT_ID.FIRST_TIME),c=1+resourceMgr.getConfigMyVIP().buyGoldBonusRate,d=0;null!=a&&(a=resourceMgr.getConfigSMSByKey(a))&&(d=a.gold*c,a=eventModule.getSpecialEventById(EVENT_ID.EXCLUSIVE_DEALS),d=a.hasEventInfo()&&a.canCompleteDeal(d)?
1:0);!d&&b.hasEventInfo()&&b.isFirstSMSAvailable()&&(c*=1+resourceMgr.getConfigEventFirstTimeSMSBonusPercent());eventModule.getSpecialEventById(SPECIAL_EVENT_ID.PURCHASE_PROMOTION).isAvailable()&&(c*=1+resourceMgr.getConfigPurchasePromotionPercent());return c},function(){var a=eventModule.getEventById(EVENT_ID.FIRST_TIME),b=playerModule.getVipLevel(),a=a.hasEventInfo()&&a.isFirstSMSAvailable()?"1":"0",c=eventModule.getSpecialEventById(SPECIAL_EVENT_ID.PURCHASE_PROMOTION).isAvailable()?"1":"0",d="";
if(0<arguments.length){var e=arguments[0],f=resourceMgr.getConfigMyVIP();if(e=resourceMgr.getConfigSMSByKey(e))d=e.gold*(1+f.buyGoldBonusRate),f=eventModule.getSpecialEventById(EVENT_ID.EXCLUSIVE_DEALS),d=f.hasEventInfo()&&f.canCompleteDeal(d)?"1":"0"}return b+a+c+d}),getTelcoPercentBonus:_.memoize(function(){var a=1+resourceMgr.getConfigMyVIP().buyGoldBonusRate;eventModule.getSpecialEventById(SPECIAL_EVENT_ID.PURCHASE_PROMOTION).isAvailable()&&(a*=1+resourceMgr.getConfigPurchasePromotionPercent());
return a},function(){var a=playerModule.getVipLevel(),b=eventModule.getSpecialEventById(SPECIAL_EVENT_ID.PURCHASE_PROMOTION).isAvailable()?"1":"0";return a+b}),getIAPPercentBonus:_.memoize(function(a){var b=playerModule.getEventById(EVENT_ID.FIRST_TIME),c=1+resourceMgr.getConfigMyVIP().buyGoldBonusRate,d=0;null!=a&&(a=resourceMgr.getConfigIAPPackByProductId(a))&&(d=a.gold*c,a=eventModule.getSpecialEventById(EVENT_ID.EXCLUSIVE_DEALS),d=a.hasEventInfo()&&a.canCompleteDeal(d)?1:0);!d&&b.hasEventInfo()&&
b.isFirstIAPAvailable()&&(c*=1+resourceMgr.getConfigEventFirstTimeIAPBonusPercent());eventModule.getSpecialEventById(SPECIAL_EVENT_ID.PURCHASE_PROMOTION).isAvailable()&&(c*=1+resourceMgr.getConfigPurchasePromotionPercent());return c},function(){var a=eventModule.getEventById(EVENT_ID.FIRST_TIME),b=playerModule.getVipLevel(),a=a.hasEventInfo()&&a.isFirstIAPAvailable()?"1":"0",c=eventModule.getSpecialEventById(SPECIAL_EVENT_ID.PURCHASE_PROMOTION).isAvailable()?"1":"0",d="";if(0<arguments.length){var e=
arguments[0],f=resourceMgr.getConfigMyVIP();if(e=resourceMgr.getConfigIAPPackByProductId(e))d=e.gold*(1+f.buyGoldBonusRate),f=eventModule.getSpecialEventById(EVENT_ID.EXCLUSIVE_DEALS),d=f.hasEventInfo()&&f.canCompleteDeal(d)?"1":"0"}return b+a+c+d})}}();
